### PR TITLE
Monitor with UI based on tui-rs

### PR DESCRIPTION
**Pull request by andreafioraldi**
atm the monitor keeps data in memory, likely will OOM on long campaign so it's not ready yet

### CODE REVIEW

**Comment by andreafioraldi** [comment]
Probably we should hide this behind a feature and disable by default (wdyt?)

**Comment by domenukk** [comment]
Very cool! We need a gif on the front readme once this is done 😎

If the dependencies take considerable time to build and /or they add a lot of size, a feature flag makes sense
Or even if not we could still have the feature flag on by default

**Comment by andreafioraldi** [comment]
Dunno why it tries to build termion (and ofc fail on windows) while I'm using the crossterm feature of tui, not termion

**Comment by andreafioraldi** [comment]
We have to hide this code under unix-only, until https://github.com/fdehau/tui-rs/issues/581 gets fixed

**Comment by andreafioraldi** [comment]
this is a first version, there are several todos but work, can be merged

Screenshot at 2022-01-20 17-57-47

**Pull request merged**
