### PR TITLE
Frida Makefile.toml fix

### PR DESCRIPTION
**Pull request by tokatoka**
On windows, it wrongly generates `frida${SEP}/target` folder now

### CODE REVIEW

**Comment by domenukk** [comment]
Oddly, you want to add
rm /usr/local/bin/2to3-*
to the ci file (and potentially others)

**Comment by tokatoka** [comment]
yes but I already merged your fix

**Comment by domenukk** [comment]
Yes but there are more broken links in your branch, you have to add these manually apparently. Maybe a hiccup in brew or GitHub actions 🥲

**Comment by tokatoka** [comment]
Fixed thanks

**Pull request merged**
