### PR TITLE
Add always_interesting option to llmp mgr

### PR DESCRIPTION
**Pull request by tokatoka**
This is for centralized

### CODE REVIEW

**Comment by tokatoka** [comment]
centralized should always set this when they create it through the Launcher. but i forgot to change that part

**Comment by domenukk** [comment]
Aaah you mean the nodes will always store new testcases, pre-filtered by centralized?

**Comment by tokatoka** [comment]
yes because that's the assumptions right?

**Comment by tokatoka** [comment]
we assume that 
"all the testcases that survive the fileters of centralized node is always intereesting, too."

**Pull request merged**
