### PR TITLE
Fix SerdeAny issue on libaf-fuzz

### PR DESCRIPTION
**Pull request by R9295**
test

### CODE REVIEW

**Comment by R9295** [comment]
lol why is cargo-fuzz failing?

**Comment by R9295** [comment]
ah thanks - will fix that

**Comment by R9295** [comment]
I think this is an issue with the new ctor

**Comment by domenukk** [comment]
Coypied from a chat:

So I think what's wrong is that impl_serdeany! uses ` #[cfg(any(not(feature = "serdeany_autoreg"), miri))]` and serdeany_autoreg is not a feature flag of the current Cargo.toml

That means we have a bug in our macro basically

We want it to self-register if serdeany_autoreg is set _for LibAFL_

It's odd it works/worked at all?

**Comment by addisoncrump** [comment]
Superceded by #2721.

**Pull request closed without merging**
