### PR TITLE
write_minibsod apple implementation proposal.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by domenukk** [comment]
Awesome! :)

**Comment by domenukk** [comment]
@devnexen what platform was this written for? It looks like it never really worked (see #2154)
cc @addisoncrump

**Comment by devnexen** [comment]
I'd say replacing target_env by target_vendor here would be appropriate ?

**Comment by domenukk** [comment]
Yes but then it doesn't build at least on M1 Mac

**Comment by devnexen** [comment]
Yes I think the libc crate had moved out mach api to the mach crate. Fixing ..

**Pull request merged**
