### PR TITLE
Lower capped RAND generators

### PR DESCRIPTION
**Pull request by CowBoy4mH3LL**
Basically, there is a `min_size` aside from the `max_size` in the RAND generators (`RandBytesGenerator` and `RandPrintablesGenerator`). 
This allows to generate rand bytes sequences from `min_size` to `max_size`, e.g. between 2 bytes and 4 bytes or 1 byte and 1 byte for that matter.
Becomes extremely useful if we are aware of the recipient's acceptance bounds.
If not, simply keep `min_size` as 1 and the older behavior is restored.

### CODE REVIEW

**Comment by tokatoka** [comment]
good.
but can you not to change the original constructor? which sets the min_size to the default value of `
and make another constructor for you, that takes two args (min and max)

**Comment by domenukk** [comment]
Yes let's add a `with_min_size` constructor instead of changing the existing API

**Comment by domenukk** [comment]
You can change one of them, for example `baby_fuzzer_custom_input` or any other of your choice :)

**Comment by domenukk** [comment]
Nice thx! :)
Clippy is still a bit unhappy:
```rust
error: this method could have a `#[must_use]` attribute
   --> libafl/src/generators/mod.rs:108:5
    |
108 |     pub fn with_min_size(min_size: NonZeroUsize, max_size: NonZeroUsize) -> Self {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: add the attribute: `#[must_use] pub fn with_min_size(min_size: NonZeroUsize, max_size: NonZeroUsize) -> Self`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#must_use_candidate
    = note: `-D clippy::must-use-candidate` implied by `-D clippy::pedantic`
    = help: to override `-D clippy::pedantic` add `#[allow(clippy::must_use_candidate)]`

error: this method could have a `#[must_use]` attribute
   --> libafl/src/generators/mod.rs:148:5
    |
148 |     pub fn with_min_size(min_size: NonZeroUsize, max_size: NonZeroUsize) -> Self {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: add the attribute: `#[must_use] pub fn with_min_size(min_size: NonZeroUsize, max_size: NonZeroUsize) -> Self`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#must_use_candidate
```

**Comment by CowBoy4mH3LL** [comment]
1. Semantically are two `must_use` attributes allowed for the same struct?
2. Can you help me with this one error - can't seem to relate to any code I introduced -- https://github.com/AFLplusplus/LibAFL/actions/runs/11757949843/job/32755797517?pr=2671

**Comment by domenukk** [comment]
The second error isn't related to your changes, sorry :)
For `must_use` it's not struct related at all, but for a method.
So just change
```rust
 pub fn with_min_size(min_size: NonZeroUsize, max_size: NonZeroUsize) -> Self {
```
to 
```rust
#[must_use]
 pub fn with_min_size(min_size: NonZeroUsize, max_size: NonZeroUsize) -> Self {
```

That should be all :)

**Comment by CowBoy4mH3LL** [comment]
Done on this one!!
Thanks guys!!
BTW, the Papa Roach stegos in the code must stay :)

**Comment by domenukk** [comment]
Thank you!

**Pull request merged**
