### PR TITLE
libafl_frida: Point to in-repo docs from API docs

### PR DESCRIPTION
**Pull request by langston-barrett**
Help users find the docs!

### CODE REVIEW

**Comment by domenukk** [comment]
The doc should make it to the book after #888 got merged and the book got published

**Comment by langston-barrett** [comment]
> The doc should make it to the book after https://github.com/AFLplusplus/LibAFL/pull/888 got merged and the book got published

Done.

**Comment by domenukk** [comment]
```rust
error: item in documentation is missing backticks
  --> libafl_frida/src/lib.rs:5:47
   |
5  | Additional documentation is available in [the LibAFL book][book].
   |                                               ^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
note: the lint level is defined here
  --> libafl_frida/src/lib.rs:12:9
   |
12 | #![deny(clippy::pedantic)]
   |         ^^^^^^^^^^^^^^^^
   = note: `#[deny(clippy::doc_markdown)]` implied by `#[deny(clippy::pedantic)]`
help: try
   |
5  | Additional documentation is available in [the `LibAFL` book][book].

```

Add the backticks around `LibAFL` then I'll merge, thx :)

**Comment by domenukk** [comment]
Also, why not make the book a "normal" link? (so `[]()`)

**Comment by domenukk** [comment]
Thank you!

**Pull request merged**
