### PR TITLE
LibAFL Atheris Compatibility

### PR DESCRIPTION
**Pull request by domenukk**
some fixes to fuzzers/libafl_atheris

### CODE REVIEW

**Comment by domenukk** [comment]
@eceo902 I'm just gonna merge this since the current fuzzer doesn't work at all, do you mind running `cargo fmt`?

**Comment by eceo902** [comment]
> @eceo902 I'm just gonna merge this since the current fuzzer doesn't work at all, do you mind running `cargo fmt`?

Just did it! Let me know if everything looks good :)

**Comment by domenukk** [comment]
Still a bunc of warnings in the libafl_atheris fuzzer:

```rust
 Checking libafl_atheris v0.11.1 (/home/runner/work/LibAFL/LibAFL/fuzzers/libafl_atheris)
error: format argument must be a string literal
  --> src/lib.rs:98:14
   |
98 |     println!(env::current_dir().unwrap().to_string_lossy().to_string());
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: you might be missing a string literal to format with
   |
98 |     println!("{}", env::current_dir().unwrap().to_string_lossy().to_string());
   |              +++++

error[E0432]: unresolved import `libafl_targets::extra_counters`
  --> src/lib.rs:42:22
   |
42 | use libafl_targets::{extra_counters, std_edges_map_observer, CmpLogObserver};
   |                      ^^^^^^^^^^^^^^ no `extra_counters` in the root
```

**Comment by eceo902** [comment]
> Still a bunc of warnings in the libafl_atheris fuzzer:

Do you know how to fix the `error[E0432]: unresolved import 'libafl_targets::extra_counters'` error? I spent some time looking into it but couldn't figure it out.

**Comment by domenukk** [comment]
Seems like it's missing the `sancov_8bit` feature for libafl_bolts (in Cargo.toml)
I'm not sure if you want 8bit cointers, but in any case that's where `extra_counters` live.

**Comment by eceo902** [comment]
> Seems like it's missing the `sancov_8bit` feature for libafl_bolts (in Cargo.toml)
> I'm not sure if you want 8bit cointers, but in any case that's where `extra_counters` live.

I fixed the println error and the extra_counters error, but now we're getting an error from the command line parsing. When running the fuzzer in practice, the fuzzer expects these flags, but I'm assuming that the tests that are failing here don't expect the flags. What is the best course of action here?

**Comment by domenukk** [comment]
Sorry I was on holidays.
CI fails right now because of a missing `cargo fmt` in the fuzzer(?)
```rust
Diff in /home/runner/work/LibAFL/LibAFL/fuzzers/libafl_atheris/src/lib.rs at line 95:
         .get_matches();
 
     let workdir = env::current_dir().unwrap();
-    println!("{}", env::current_dir().unwrap().to_string_lossy().to_string());
+    println!(
+        "{}",
+        env::current_dir().unwrap().to_string_lossy().to_string()
+    );
 
     let cores = Cores::from_cmdline(matches.get_one::<String>("cores").unwrap())
         .expect("No valid core count given!");    
```

Regarding the command line, aren't we the ones writing both sides? Just fix it on the test side?

**Comment by domenukk** [comment]
@eceo902 what's the status? Thx :)

**Comment by domenukk** [comment]
I will merge this as-is, then?

**Pull request merged**
