### PR TITLE
compression fix

### LINKED ISSUE #167: mozjpeg is crashing
```
[/home/andrea/Desktop/LibAFL/libafl/src/events/llmp.rs:810] "Spawning next client (id {})" = "Spawning next client (id {})"
[/home/andrea/Desktop/LibAFL/libafl/src/events/llmp.rs:810] ctr = 0
We're a client, let's fuzz :)
First run. Let's set it all up
We're a client, let's fuzz :)
Loading file "./corpus/blank.jpg" ...
thread '<unnamed>' panicked at 'index out of bounds: the len is 19 but the index is 224', /home/andrea/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.5/src/deflate/encoder.rs:342:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:69:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:188:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:26:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2188:9
   6: compression::deflate::encoder::InflaterInner::enc_tab_to_freq
             at /home/andrea/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.5/src/deflate/encoder.rs:342:21
   7: compression::deflate::encoder::InflaterInner::create_custom_huffman_table
             at /home/andrea/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.5/src/deflate/encoder.rs:383:34
   8: compression::deflate::encoder::InflaterInner::write_block
             at /home/andrea/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.5/src/deflate/encoder.rs:457:13
   9: compression::deflate::encoder::InflaterInner::next
             at /home/andrea/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.5/src/deflate/encoder.rs:593:13
  10: compression::deflate::encoder::Inflater::next_bits
             at /home/andrea/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.5/src/deflate/encoder.rs:164:37
  11: <compression::deflate::encoder::Inflater as compression::traits::encoder::Encoder>::next
             at /home/andrea/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.5/src/deflate/encoder.rs:212:27
  12: <compression::gzip::encoder::GZipEncoder as compression::traits::encoder::Encoder>::next
             at /home/andrea/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.5/src/gzip/encoder.rs:116:23
  13: <compression::traits::encoder::EncodeIterator<I,E> as core::iter::traits::iterator::Iterator>::next
             at /home/andrea/.cargo/registry/src/github.com-1ecc6299db9ec823/compression-0.1.5/src/traits/encoder.rs:77:9
  14: core::iter::traits::iterator::Iterator::try_fold
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1982:29
  15: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::try_fold
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:170:9
  16: core::iter::traits::iterator::Iterator::find
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2335:9
  17: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:152:9
  18: alloc::vec::Vec<T,A>::extend_desugared
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2291:35
  19: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_extend.rs:18:9
  20: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs:37:9
  21: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs:36:9
  22: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2196:9
  23: core::iter::traits::iterator::Iterator::collect
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1765:9
  24: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1554:53
  25: core::iter::adapters::process_results
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:141:17
  26: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1554:9
  27: core::iter::traits::iterator::Iterator::collect
             at /home/andrea/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1765:9
  28: libafl::bolts::compress::GzipCompressor::compress
             at /home/andrea/Desktop/LibAFL/libafl/src/bolts/compress.rs:33:30
  29: <libafl::events::llmp::LlmpEventManager<I,OT,S,SP> as libafl::events::EventFirer<I,S>>::fire
             at /home/andrea/Desktop/LibAFL/libafl/src/events/llmp.rs:400:15
  30: <libafl::events::llmp::LlmpRestartingEventManager<I,OT,S,SP> as libafl::events::EventFirer<I,S>>::fire
             at /home/andrea/Desktop/LibAFL/libafl/src/events/llmp.rs:545:9
  31: <libafl::fuzzer::StdFuzzer<C,CS,F,I,OF,OT,S,SC> as libafl::fuzzer::Evaluator<E,EM,I,S>>::evaluate_input
             at /home/andrea/Desktop/LibAFL/libafl/src/fuzzer.rs:374:17
  32: libafl::state::StdState<C,FT,I,R,SC>::load_from_directory
             at /home/andrea/Desktop/LibAFL/libafl/src/state/mod.rs:389:25
  33: libafl::state::StdState<C,FT,I,R,SC>::load_initial_inputs_internal
             at /home/andrea/Desktop/LibAFL/libafl/src/state/mod.rs:417:13
  34: libafl::state::StdState<C,FT,I,R,SC>::load_initial_inputs
             at /home/andrea/Desktop/LibAFL/libafl/src/state/mod.rs:460:9
  35: libfuzzer_libmozjpeg::fuzz
             at ./src/lib.rs:157:9
  36: main
             at ./src/lib.rs:48:5
  37: __libc_start_main
  38: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Crashed with SIGABRT
Double crash
```

Can somebody try to reproduce it?

### PR DESCRIPTION
**Pull request by tokatoka**
This should fix #167 
I decided to use another library for GZip compression/decompression

### CODE REVIEW

**Comment by tokatoka** [comment]
ah, ... 'no_std'
Can I make llmp_compresssion std-only feature? @domenukk

**Comment by domenukk** [comment]
There are plenty of no_std compression libs, right? 😬 Does it really solve the issue?

**Comment by tokatoka** [comment]
I'll try others

**Comment by domenukk** [comment]
Worst case we can drop no_std compression for now, we don't really have llmp no_std users (yet) anyway

**Comment by tokatoka** [comment]
It should be good with no_std now.
With an image attached to LLMP Event this one saves a tremendous amount of memory usage (around 1/50 ~ 1/100 compared to no compression)

**Comment by domenukk** [comment]
Sounds really good but should like we should set up a `cargo bench` for compression libs eventually, optimizing for decompression speeds 😁

**Pull request merged**
