### PR TITLE
Cmplog New Pass Manager & LLVM 14 Fixes

### PR DESCRIPTION
**Pull request by tokatoka**
- use the new pm in cmplog routines.
- fixes for llvm ver 14
- auto-select to use new pm when llvm version is >= 14

### CODE REVIEW

**Comment by tokatoka** [comment]
Closes #476

**Comment by tokatoka** [comment]
It does not get past this line, and the llvm passes are not built.
https://github.com/AFLplusplus/LibAFL/blob/main/libafl_cc/build.rs#L115

**Comment by andreafioraldi** [comment]
> 

IIRC it was working last time I checked using https://llvm.org/builds/

**Comment by tokatoka** [comment]
I used the installer but no llvm-config was installed. (same for the gh workflow vm, llvm-config is not available)
I remember rich was also talking about this..

but I think we can modify libafl_cc to build the llvm passes even if there's no llvm-config.

**Comment by andreafioraldi** [comment]
> 

Yes we can rely on the installation dir, maybe with an LLVM_DIR env

**Comment by tokatoka** [comment]
can we merge this?
llvm installation path issue should be done in another PR.

**Comment by domenukk** [comment]
Maybe we want to open an issue for it, too?

**Pull request merged**
