### PR TITLE
libafl_nyx: Add support for `StdOutObserver`

### PR DESCRIPTION
**Pull request by l4yton**

### CODE REVIEW

**Comment by domenukk** [comment]
Looks good, thanks!
I wonder what the parent_cpu removal means in practice (I'm not using libafl_nyx much tbh)

**Comment by l4yton** [comment]
> I wonder what the parent_cpu removal means in practice (I'm not using libafl_nyx much tbh)

Ah yeah, I probably should have explained that :)
The previous libnyx version had different `NyxProcess` constructors, so for example `NyxProcess::create_parent_process` would create the fuzzing snapshot and `NyxProcess::create_child_procss` use it. And as far as I understand, this is now done internally, so if no fuzzing snapshot exists, the first `NyxProcess` will create one and every other `NyxProcess` will use it.
Since `parent_cpu_id` was used to specify which process should create the fuzzing snapshot, this makes it obsolete.

**Comment by l4yton** [comment]
Ok, I think I might be wrong. Will have to check later.

**Comment by l4yton** [comment]
Should be fixed now

**Comment by domenukk** [comment]
thanks! :)

**Pull request merged**
