### PR TITLE
Mark AsanErrors::get_mut unsafe

### PR DESCRIPTION
**Pull request by domenukk**
The API accesses a static...

### CODE REVIEW

**Comment by domenukk** [comment]
@s1341 Should the variable be behind a Mutex? I guess the hooks could _in theory_ trigger at the same time if we are stalking multiple threads(?)

**Comment by domenukk** [comment]
This also needs #1987 to compile properly

**Comment by s1341** [comment]
I don't think it needs a mutex, as it the fuzzer is single-threaded, and we only check for leaks after the execution of the target harness.

**Comment by domenukk** [comment]
> I don't think it needs a mutex, as it the fuzzer is single-threaded, and we only check for leaks after the execution of the target harness.

Shoudn't it _in theory_ support multi-threaded targets?

**Comment by s1341** [comment]
I guess so... still not certain we need a mutex here though.

**Comment by s1341** [comment]
Ok. so let's add a mutex.

**Comment by domenukk** [comment]
API is safe with #1995 so closing this

**Pull request closed without merging**
