### PR TITLE
0.8.1 Release

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

**Comment by domenukk** [comment]
So should we add cargo-libafl to the main repo? CC @andreafioraldi

**Comment by tokatoka** [comment]
I agree with domenukk's idea

**Comment by andreafioraldi** [comment]
> So should we add cargo-libafl to the main repo? CC @andreafioraldi

fine for me

**Comment by andreafioraldi** [comment]
i'll merge and release this one before

**Pull request merged**
