### PR TITLE
Add Features for C Targets

### PR DESCRIPTION
**Pull request by novafacing**
Moves C-compiled targets and extern items behind features in libafl_targets. On Windows, these don't all compile correctly or with all toolchains. Right now, they have to be compiled to use the CMP observers in libafl_targets, this just makes it so you can use the observers without needing the C compile steps.

### CODE REVIEW

**Comment by domenukk** [comment]
Not a very helpful error message, bug this still seems to fail:
```rust
error: process didn't exit successfully: `/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo check --manifest-path libafl_targets/Cargo.toml --no-default-features --features sancov_pcguard` (exit status: 101)
Error: Process completed with exit code 1.
```

**Comment by novafacing** [comment]
I think I know why, I think some cfg is in the wrong order, I'll fix it today 🙂

**Comment by domenukk** [comment]
Ping :)

**Comment by domenukk** [comment]
```rust
running `cargo check --no-default-features --features sancov_pcguard` on libafl_targets (80/121)
     Compiling libafl_targets v0.11.1 (/home/runner/work/LibAFL/LibAFL/libafl_targets)
  warning: unused variable: `src_dir`
    --> libafl_targets/build.rs:10:9
     |
  10 |     let src_dir = Path::new("src");
     |         ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_src_dir`
     |
     = note: `#[warn(unused_variables)]` on by default
  
  warning: `libafl_targets` (build script) generated 1 warning
  error[E0432]: unresolved import `crate::coverage`
   --> libafl_targets/src/sancov_pcguard.rs:3:12
    |
  3 | use crate::coverage::{EDGES_MAP, MAX_EDGES_NUM};
    |            ^^^^^^^^ could not find `coverage` in the crate root
  
  For more information about this error, try `rustc --explain E0432`.
  error: could not compile `libafl_targets` (lib) due to previous error
error: process didn't exit successfully: `/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo check --manifest-path libafl_targets/Cargo.toml --no-default-features --features sancov_pcguard` (exit status: 101)
Error: Process completed with exit code 1.
```

Still fails :)

**Comment by domenukk** [comment]
Looks like `sancov_pcguard` should depend on `coverage`

**Comment by domenukk** [comment]
Thanks!

**Pull request merged**
