### PR TITLE
Add `serdeany_autoreg` to `libafl_qemu`

### PR DESCRIPTION
**Pull request by d0ntrash**
Fix `Cannot deserialize an unregistered type` occurring when using libafl_qemu.

### CODE REVIEW

**Comment by andreafioraldi** [comment]
@domenukk isn't serdeany_autoreg in default?

**Comment by domenukk** [comment]
Yes, but this uses
`libafl_bolts = { path = "../libafl_bolts", version = "0.10.1", default-features = false, features = ["std", "derive"] }`

**Comment by domenukk** [comment]
We should totally put it in `default` here as well

**Comment by domenukk** [comment]
Done :)
Thanks for the fix @d0ntrash

**Pull request merged**
