### PR TITLE
Companion patch to qemu-libafl-bridge #46

### PR DESCRIPTION
**Pull request by cube0x8**
Fixing out-of-bound read on qemu-libafl-bridge snapshot creation [(qemu PR)](https://github.com/AFLplusplus/qemu-libafl-bridge/pull/47)

### CODE REVIEW

**Comment by tokatoka** [comment]
can you cargo fmt? (nightly)

**Comment by andreafioraldi** [comment]
@cube0x8 to include your patch to qemu change libafl_qemu_build/src/build.rs and use this commit id `194b3a987c751f98c0db0f3537fa789b43b4e663`, then i'll merge

**Comment by domenukk** [comment]
Merging this since @andreafioraldi said it's fine

**Comment by domenukk** [comment]
Reverting this, see https://github.com/AFLplusplus/LibAFL/pull/1806#issuecomment-1949217542

**Pull request merged**
