### PR TITLE
Asynchronous executors

### PR DESCRIPTION
**Pull request by addisoncrump**
This PR introduces asynchronous executors will task batching for use with asynchronous execution environments. This enables many new use cases, including (but not limited to):

 - distributed executors (fuzzer pipeline hosted on a single machine, executors distributed over multiple)
 - differential execution over diverse platforms (e.g., diff fuzzing a macOS target and a Windows target)
 - use of std fuzzer pipelines with no-std environments (e.g., low-level fuzzing with testcases submitted over a channel)

The process for performing asynchronous fuzzing prefers task batching. This is done using `DeferredExecutionResult` and expects each stage to offer a batching execution where possible, e.g. for a mutational stage:

 1. Determine how many mutations will be created (n)
 2. Allocate space for n `DeferredExecutionResult`s
 3. For each mutation:
    1. Mutate the input
    2. Start the execution on the executor and stash the `DeferredExecutionResult`
 4. For each `DeferredExecutionResult`:
    1. Get the result
    2. Check the interestingness with the associated feedback

Because a blanket impl of `AsyncExecutor` exists for all `Executor`s with observers, synchronous executors may be used in an asynchronous pipeline at the cost of an extra clone of the observers. Additionally, `AsyncBridge` may be used to use asynchronous executors in a synchronous pipeline, but may suffer execution speed due to being used without batching.

### CODE REVIEW

**Comment by domenukk** [comment]
Cc @epi052 you may like this

**Comment by VTCAKAVSMoACE** [comment]
Well, the CI is broken, but I've tested the fuzzers locally and they do be worky :+1:

**Comment by VTCAKAVSMoACE** [comment]
This is still missing a lot of perf items and such which are likely desirable for introspection. Working on that still, but it's in a semi-stable state.

**Comment by VTCAKAVSMoACE** [comment]
Stages that need async support (check is complete, cross-out is deemed impossible):

- [ ] CalibrationStage
- [ ] ClosureStage
- [ ] ConcolicTracingStage
- [ ] DumpToDiskStage
- [ ] GeneralizationStage
- [x] PowerMutationalStage
- [ ] PushStageAdapter
- [ ] SimpleConcolicMutationalStage
- [ ] SkippableStage
- [x] StdMutationalStage
- [ ] StdTMinMutationalStage
- [ ] SyncFromDiskStage
- [ ] TracingStage
- [ ] TuneableMutationalStage
- [ ] ShadowTracingStage

**Comment by domenukk** [comment]
Is this ready to merge?

**Comment by VTCAKAVSMoACE** [comment]
No, I need to complete the checklist above.

**Comment by domenukk** [comment]
Closing this, a lot has happened since. Feel free to reopen if it's still relevant.

**Pull request closed without merging**
