### PR TITLE
Warn on missing testcase after fuzz run

### PR DESCRIPTION
**Pull request by domenukk**
How about this as follow-up for #1717 ?

### CODE REVIEW

**Comment by tokatoka** [comment]
i think we should return Error

**Comment by domenukk** [comment]
Not sure if it should be an error tbh, it's what the user wants in this case.
Or maybe an error that's recoverable then?

**Comment by tokatoka** [comment]
i think if the testcase for idx does not exist, then users should fix it asap because some parts of our assume that that idx exists. (like Tmin)

**Comment by domenukk** [comment]
This only happens when the testcase gets removed during the stage, and then it's expected

**Comment by domenukk** [comment]
> i don't know. i think it should be either 1) return an error so that users can handle and fix asap or 2) simply warns nothing about it.

Then closing this

**Pull request closed without merging**
