### PR TITLE
Update pyo3 crate to 0.18.3

### PR DESCRIPTION
**Pull request by twizmwazin**

### CODE REVIEW

**Comment by twizmwazin** [comment]
It seems the build failure is due to nautilus depending on pyo3 0.17 still. There is a [PR](https://github.com/nautilus-fuzz/nautilus/pull/40) over there to update to 0.18.2, but it doesn't look like the maintainers have touched the project in a while. Commenting out the grammartec dependency in Cargo.toml as well as the nautilus and AGPL features. I was able to get this to build. I'm not terribly proficient in Cargo so I'm unsure what the correct way to solve this is.

**Comment by tokatoka** [comment]
@andreafioraldi is a maintainer

**Comment by andreafioraldi** [comment]
nautilus 0.3.1 released with the updated pyo3

**Comment by tokatoka** [comment]
it seems good
can i merge @twizmwazin

**Comment by twizmwazin** [comment]
Yep!

**Pull request merged**
