### PR TITLE
bolts for haiku update.

### PR DESCRIPTION
**Pull request by devnexen**
core_affinity using available_parallelism which also support this platform. further tests disabling.

### CODE REVIEW

**Comment by domenukk** [comment]
Thanks! Looks like it needs a little `cargo fmt` :)

**Comment by domenukk** [comment]
FreeBSD now fails?
```rust
  test shmem::tests::test_shmem_service ... ok
  
  failures:
  
  ---- core_affinity::tests::test_get_core_ids stdout ----
  thread 'core_affinity::tests::test_get_core_ids' panicked at libafl_bolts/src/core_affinity.rs:939:9:
  assertion `left == right` failed
    left: 2
   right: 1
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  
  
  failures:
      core_affinity::tests::test_get_core_ids
  
  test result: FAILED. 20 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.19s
  
  error: test failed, to rerun pass `-p libafl_bolts --lib`
```

**Comment by domenukk** [comment]
Maybe we should disable that test?

**Comment by devnexen** [comment]
ah here we go again..

**Pull request merged**
