### PR TITLE
Update deps for libafl

### PR DESCRIPTION
**Pull request by rchildre3**
Reduces total number of packages from 577 to 571 on building with: `cargo +nightly build --workspace --all-features`

* ahash 0.7 -> 0.8
  * Move `AHasher::new_with_keys` to `RandomState::with_seeds` given the recommendation from: aHash maintainer: https://github.com/tkaitchuck/aHash/issues/132#issuecomment-1288207069

* bindgen: 0.61 -> 0.63

* c2rust-bitfields: 0.3 -> 0.17

* criterion: 0.3 -> 0.4

* crossterm: 0.25 -> 0.26

* dynasmrt: 1.2 -> 2

* frida-gum/frida-gum-sys
  * frida-gum:     0.8.1 -> 0.10
  * frida-gum-sys: 0.4.1 => 0.6
  * Update underlying frida version from 15.2 -> 16.0

* goblin: 0.5.3 -> 0.6

* hashbrown: 0.12 -> 0.13

* nix: 0.25 -> 0.26
  * The `addr` arg of `mmap` is now of type `Option<NonZeroUsize>`
  * The `length` arg of `mmap` is now of type `NonZeroUsize`

* prometheus-client: 0.18.0 -> 0.19
  * Do not box metrics
  * Gauges (a majority of the LibAFL metrics) are now i64 types so there is a small chance of overflow, with the u64 values that LibAFL tracks, but unlikely to be problematic.
 * Keep `exec_rate` as a floating point value

* serial_test: 0.8 -> 1

* typed-builder: 0.10.0 -> 0.12

* windows: 0.42.0 -> 0.44

### CODE REVIEW

**Comment by domenukk** [comment]
We can't update frida befor the capstone changes in https://github.com/capstone-rust/capstone-rs/pull/140 are merged, see
#1018 and https://github.com/frida/frida-rust/issues/81

**Comment by domenukk** [comment]
```rust
    Checking forkserver_libafl_cc v0.8.2 (/home/runner/work/LibAFL/LibAFL/fuzzers/forkserver_libafl_cc)
error[E0308]: mismatched types
   --> src/main.rs:188:9
    |
185 |     let mut executor = TimeoutForkserverExecutor::with_signal(
    |                        -------------------------------------- arguments to this function are incorrect
...
188 |         opt.signal,
    |         ^^^^^^^^^^ expected enum `nix::sys::signal::Signal`, found a different enum `nix::sys::signal::Signal`
    |
    = note: enum `nix::sys::signal::Signal` and enum `nix::sys::signal::Signal` have similar names, but are actually distinct types
note: enum `nix::sys::signal::Signal` is defined in crate `nix`
```

Sounds like there are now two versions of the nix crate linked for this fuzzer

If you fix this and revert frida, I'll merge, thanks! :)

**Comment by rchildre3** [comment]
Fixed in 694aa1e836f415fdc81cfa73ce1b938efb32ca3f

**Comment by domenukk** [comment]
Weird errors in CI now

**Comment by domenukk** [comment]
```rust
Compiling symcc_libafl v0.9.0 (/home/runner/work/LibAFL/LibAFL/libafl_concolic/symcc_libafl)
error[E0425]: cannot find function `clang_CXXMethod_isVirtual` in this scope
    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.58.1/src/clang.rs:673:18
     |
673  |           unsafe { clang_CXXMethod_isVirtual(self.x) != 0 }
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `clang_CXXMethod_isPureVirtual`
     |
    ::: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.5.1/src/lib.rs:1735:1
```

**Comment by domenukk** [comment]
Seems like the Bingen API changed? Or symcc also needs a Bingen update(?)

**Comment by domenukk** [comment]
Seems to be broken in main as well, so merging this now and trying to fix it after

**Pull request merged**
