### PR TITLE
Add signal option to forkserver_simple

### PR DESCRIPTION
**Pull request by tklengyel**

### CODE REVIEW

**Comment by tokatoka** [comment]
hi, thank you for your pr!
please run `cargo fmt` in `fuzzers/forkserver_simple` to make it pass ci tests

**Comment by domenukk** [comment]
For future reference, no need to force push of that makes it easier, we always squash before merge :)

**Comment by tklengyel** [comment]
I always squash fixups as a matter of habit :)

**Comment by domenukk** [comment]
Thanks! :)

**Pull request merged**
