### PR TITLE
Windows CI

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

**Comment by domenukk** [comment]
Why close?

**Comment by tokatoka** [comment]
I thought it is not as easy as uncommenting two lines if clang/llvm is missing
and thus I have to search more about about this. (and so it would be better to try things in a cloned repo of mine)

**Comment by domenukk** [comment]
Up to you :)
But leaving this open as draft pr would be fine too

**Comment by tokatoka** [comment]
We can build libafl_frida (not frida_libpng), and that should work

**Comment by tokatoka** [comment]
Doesn't work😩

**Pull request closed without merging**
