### PR TITLE
Trying to redo workspace deps

### PR DESCRIPTION
**Pull request by domenukk**
This tries to un-undo #2652

### CODE REVIEW

**Comment by domenukk** [comment]
@tokatoka I'm stuck on ahash-> foldhash, you did that already right?

**Comment by tokatoka** [comment]
no i didn't
i only changed hashbrown's feature flag

**Comment by domenukk** [comment]
Ah dang. I think switching the whole codebase is the right thing to do, but I'm a bit stuck

**Comment by tokatoka** [comment]
see discord. i don't think we should change to foldhash now

**Comment by domenukk** [comment]
Restarting without chaging the hashbrown version

**Comment by domenukk** [comment]
We won't update hashbrown and switch our hashing function (as I tried in #2672) to 0.15 until this issue looks better https://github.com/rust-lang/hashbrown/issues/577

**Comment by domenukk** [comment]
Continuing this in  #2673 instead

**Pull request closed without merging**
