### PR TITLE
add `pre-commit` support

### PR DESCRIPTION
**Pull request by syheliel**
1. `pip install pre-commit`
2. run `pre-commit install` to install the git hook

you will run `cargo fmt` and `cargo check` when you commit each time.

### CODE REVIEW

**Comment by domenukk** [comment]
I've never used this, what's the benefit over manually running `cargo fmt` before push?

**Comment by syheliel** [comment]
> I've never used this, what's the benefit over manually running `cargo fmt` before push?

just automate the `cargo fmt` step, good for new contributor

**Comment by domenukk** [comment]
But only if they have that tool installed, correct?

**Comment by syheliel** [comment]
> But only if they have that tool installed, correct?

Yes, what 'pre-commit' do is to create '.git/hooks/', this is not traced by git.

**Comment by domenukk** [comment]
I'm not sure adding pre-commit is worth it  just to run `cargo fmt`.. Closing for now, but open to discussions. :)

**Pull request closed without merging**
