### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by tokatoka**
We really need CI for frida windows. This is so fragile

### CODE REVIEW

**Comment by domenukk** [comment]
At least building LibAFL Frida on windows should already be in ci, no?

**Comment by tokatoka** [comment]
I guess no
https://github.com/AFLplusplus/LibAFL/blob/main/.github/workflows/build_and_test.yml#L135-L151
the workflow is commented out

**Comment by tokatoka** [comment]
we can just enable this?

**Comment by domenukk** [comment]
Ah maybe it needs LLVM and I couldn't get the correct path (or something)

**Comment by tokatoka** [comment]
I see..

**Pull request merged**
