### PR TITLE
fix all the fuzzers links in the libafl book

### PR DESCRIPTION
**Pull request by marcograss**
* fixed the links in the different sections of the book, the fuzzers have since then moved to subfolders

### CODE REVIEW

**Comment by domenukk** [comment]
Thanks! Looks like removing the `extern crate`s broke compilation in the book, though(?)

@rmalmain @tokatoka be careful when moving the fuzzers in the future :)

**Comment by marcograss** [comment]
> Thanks! Looks like removing the `extern crate`s broke compilation in the book, though(?)
> 
> @rmalmain @tokatoka be careful when moving the fuzzers in the future :)

ops, I didn't have this mdbook check installed and I didn't see it. I reverted the culprit commit

**Comment by rmalmain** [comment]
> Thanks! Looks like removing the `extern crate`s broke compilation in the book, though(?)
> 
> @rmalmain @tokatoka be careful when moving the fuzzers in the future :)

opened #2495 to avoid this problem in the future

**Comment by rmalmain** [comment]
i'll fix the broken links not fixed here

**Pull request merged**
