### PR TITLE
Fixing CI from #559

### PR DESCRIPTION
**Pull request by domenukk**
This PR aims to fix the CI regression introduced in #559

### CODE REVIEW

**Comment by domenukk** [comment]
@julihoh I don't seem to be able to run the smoke test locally, it errors out with
```bash
+ symcc_build/symcc symcc/test/if.c -o if
./smoke_test.sh: line 40: symcc_build/symcc: No such file or directory
```
Any ideas what I'm doing wrong?

**Comment by domenukk** [comment]
After updating to the latest symcc, build fails with:
```
...
  [100%] Linking CXX shared module libSymbolize.so
  [100%] Built target Symbolize
  cargo:root=/home/runner/work/LibAFL/LibAFL/fuzzers/libfuzzer_stb_image_concolic/fuzzer/target/debug/build/libfuzzer_stb_image_concolic-e03ca9b91d6514ca/out
  cargo:warning=Runtime not found. Build it first.
...
```

Anybody here who knows more about about the concolic stuff? CC @julihoh @shouc

**Comment by julihoh** [comment]
Regarding the last (macOS) CI failure: I think the concolic fuzzer should be excluded from macOS CI. I don't think SymCC is really going to work there and it's not tested/intended to work there at all.

**Comment by tokatoka** [comment]
I changed Makefile.toml to make it linux-only.

**Pull request merged**
