### PR TITLE
Remove capstone from frida [aarch64]

### PR DESCRIPTION
**Pull request by mineo333**
Not done yet, but this PR removes capstone from libafl-frida for aarch64. 

The changes themselves are mostly done, but it needs to be tested and some tests need to be added. The API also needs to be made consistent with https://github.com/AFLplusplus/LibAFL/pull/1720 to the extent possible.

### CODE REVIEW

**Comment by s1341** [comment]
Looks like a good start... Have you tested at all?

**Comment by mineo333** [comment]
> Looks like a good start... Have you tested at all?

As of right now, the ASAN changes themselves seem to be in an OK state. They are able to detect memory errors in a small UAF harness that I wrote and they also pass the tests here: https://github.com/AFLplusplus/LibAFL/blob/002656b076d70da9855111df5fc0feb1c44ba099/libafl_frida/src/asan/asan_rt.rs#L198-L270

**Comment by s1341** [comment]
It would be great if we could think of a way to implement some CI-time tests for this stuff... I'm open to suggestions.

**Comment by domenukk** [comment]
The `cargo make test` for fuzzers in makefile.toml are our current way to do CI-time testing, if it finds an objective it's deemed correct

**Pull request merged**
