### PR TITLE
Replace uses std HashMap with hashbrown for consistency

### PR DESCRIPTION
**Pull request by domenukk**
We use it everywhere so we should continue doing so. We should especially not mix and match both.

### CODE REVIEW

**Comment by rmalmain** [comment]
maybe its time for me to merge at least by benches on hashmaps

**Comment by rmalmain** [comment]
long story short, the (current) fastest hashmap for integer key is `FxHashMap` from what I've measured so far

**Comment by domenukk** [comment]
> long story short, the (current) fastest hashmap for integer key is `FxHashMap` from what I've measured so far

Is it `no_std` compatible?

**Comment by domenukk** [comment]
Also, I'd say the only "real" benchmark for this is a fuzzbench run

**Pull request merged**
