### PR TITLE
implemented MapMaxPow2Feedback

### PR DESCRIPTION
**Pull request by domenukk**
This adds a new feedback that only tracks new testcases if the edges count has at least a pow2 distance to the last

### CODE REVIEW

**Comment by andreafioraldi** [comment]
Why a new feedback? You can filter in the observer, see the HitcountsMapObserver

**Comment by domenukk** [comment]
Filtering the feedback makes sense in general, I think. I forgot the observer does this internally, and it seems counter intuitive to have an active observer - but the impl is probably more performant.
Anyway, why not have both? The feedback will work with any int type

**Comment by domenukk** [comment]
@andreafioraldi added a OneOrFilled filter, maybe this makes some sense, at least for minimizing number of corpus entires

**Comment by andreafioraldi** [comment]
> @andreafioraldi added a OneOrFilled filter, maybe this makes some sense, at least for minimizing number of corpus entires

For me it's better to have in the observer, so that when the observed is serialized for LLMP is already ready and the other clients avoid to filter again

**Comment by domenukk** [comment]
other clients might use other feedbacks and strategies. Since It shouldn't have runtime overhead if it's not being used, why not offer both?

**Comment by domenukk** [comment]
@andreafioraldi any reason against the filters? It's flexibility and doesn't cost much (apart from adding another generic..)

**Pull request merged**
