### PR TITLE
Cmplog Ctx

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

**Comment by andreafioraldi** [comment]
why COVERAGE_MAP_SIZE? use the cmplog map size to generate the IDs

**Comment by tokatoka** [comment]
ok

**Comment by tokatoka** [comment]
what is the purpose of fuzzers/fuzzbench/stub.c
does this serve the same purpose of libafl_cc/no-link-rt.c?

**Comment by tokatoka** [comment]
@andreafioraldi

**Comment by tokatoka** [comment]
i have to do this for cmplog routines too, :weary: :weary: :weary:

**Comment by domenukk** [comment]
What's the status? Merge?

**Comment by tokatoka** [comment]
let's see after another fuzzbench run

**Pull request closed without merging**
