### PR TITLE
TinyInst Update

### PR DESCRIPTION
**Pull request by tokatoka**
TinyInst update and one bug fixing in simple event monitor

## TODO
- [x] CI
- [x] shmem testcase passing
- [x] Doc (maybe add another chapter to libafl book)

### CODE REVIEW

**Comment by domenukk** [comment]
Btw is this seems to be windows only atm, but MacOS could "just work", right?

**Comment by domenukk** [comment]
What's the status here? We should include it for 0.9 :)

**Comment by elbiazo** [comment]
Also @tokatoka The tinyinst-rs project is still under my repo but I think it would make more sense for AFLplusplus to have it kind of like unicornafl.

**Comment by tokatoka** [comment]
Sorry I forgot to respond to the latest message.
> Btw is this seems to be windows only atm, but MacOS could "just work", right?

Yes the lib is ready, but we need something different for the harness and the build script

> Also @tokatoka The tinyinst-rs project is still under my repo but I think it would make more sense for AFLplusplus to have it kind of like unicornafl.

Can you clone this repo https://github.com/elbiazo/tinyinst-rs? in AFLplusplus @domenukk @andreafioraldi

**Comment by tokatoka** [comment]
Do we want to clone this too? 
https://github.com/elbiazo/TinyInst/commits/master

**Comment by domenukk** [comment]
We should try to work with upstream tinyinst if possible y imho. Adding a few lines to cake could be done in build.rs(?)

**Comment by elbiazo** [comment]
I agree. I don't think we want to clone Tinyinst. It should be possible to either diff or copy all the file we need and just copy it from Tinyinst-rs

**Comment by domenukk** [comment]
What's missing here to merge the current state?

**Comment by elbiazo** [comment]
> We should try to work with upstream tinyinst if possible y imho. Adding a few lines to cake could be done in build.rs(?)

Working on this now. link to issue here. https://github.com/AFLplusplus/tinyinst-rs/issues/2 . I will also try to add macos support after that.

**Comment by elbiazo** [comment]
> > We should try to work with upstream tinyinst if possible y imho. Adding a few lines to cake could be done in build.rs(?)
> 
> Working on this now. link to issue here. [AFLplusplus/tinyinst-rs#2](https://github.com/AFLplusplus/tinyinst-rs/issues/2) . I will also try to add macos support after that.

Here are all the fix to what we discussed earlier.

[macos support pr](https://github.com/AFLplusplus/tinyinst-rs/pull/5)
[build.rs update and working with tinyinst upstream pr](https://github.com/AFLplusplus/tinyinst-rs/issues/2)

**Comment by domenukk** [comment]
Nice work!

**Pull request merged**
