### PR TITLE
chore(drcov_rt): remove unused a field and methods

### PR DESCRIPTION
**Pull request by saruman9**
Update after https://github.com/AFLplusplus/LibAFL/pull/1579.

### CODE REVIEW

**Comment by s1341** [comment]
How are you mapping stalked addresses to real addresses without this?

**Comment by tokatoka** [comment]
> How are you mapping stalked addresses to real addresses without this?

Is address real address or stalked address in #1579

**Comment by saruman9** [comment]
@s1341, @tokatoka, I assume that I'm using a real address in #1579. At least in practice (I found out with the help of logging messages) I see that a real address is being used. Why a stalked address was used earlier --- I don't know.

After the modifications I made, I take off a coverage many times and it was correct (previously, all the coverages were incorrect, IDA / Binary Ninja / Ghidra could not even open them because the addresses did not match).

**Comment by domenukk** [comment]
Thank you!

**Pull request merged**
