### PR TITLE
Launcher example needs --cores

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

**Comment by tokatoka** [comment]
#187

**Comment by domenukk** [comment]
Any idea why the the CI didn't turn red btw?

**Comment by tokatoka** [comment]
I'm not sure but maybe timeout always return exit code 0?

**Comment by tokatoka** [comment]
not really, it's from mozjpeg's broker and it's returning exit code 124

**Comment by domenukk** [comment]
Thx :)

**Comment by tokatoka** [comment]
With tests written in Makefile, we can test the failures in the broker at most.
Failures in clients can't be detected with exit code (we're just asked to type `QUIT`)

**Pull request merged**
