### PR TITLE
Run qemu_systemmode tests with self-hosted runners

### PR DESCRIPTION
**Pull request by rmalmain**
Also, rename `test_all_fuzzers.sh` into `test_fuzzer.sh`

### CODE REVIEW

**Comment by domenukk** [comment]
test_fuzzer_s_.sh? It doesn't just test a single one?

**Comment by tokatoka** [comment]
@domenukk 
I changed the ci so that one CI instance will only test one fuzzer.
test_all_fuzzers.sh accept argv[1] which is the sole fuzzer to run for that specific CI instance. Hence it is test_fuzzer.sh

**Comment by domenukk** [comment]
Is there a way to run this locally still/bring back test_all_fuzzers.sh as wrapper?

**Comment by tokatoka** [comment]
@rmalmain 
can you add this to line 9 of test_all_fuzzers.sh?
```
    fuzzers=$(find ./fuzzers -mindepth 1 -maxdepth 1 -type d)
    backtrace_fuzzers=$(find ./fuzzers/backtrace_baby_fuzzers -mindepth 1 -maxdepth 1 -type d)
    fuzzer_to_test="$fuzzers $backtrace_fuzzers"
```

**Pull request merged**
