### PR TITLE
Update FreeBSD on CI

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by domenukk** [comment]
You could comment out all non-freebsd CI tasks for testing

**Comment by devnexen** [comment]
after several attemps, did not get any failure.

**Comment by domenukk** [comment]
Yeah, it seems to be a rare case. Maybe a bug in the standard library or something? Or could the VM pause and resume?

**Comment by devnexen** [comment]
I ve read the freebsd implementation, I see nothing wrong (there is even a fallback) but I recall there was an update/rewrite on the affinity api between 13.1/13.2 maybe there is that but maybe not related at all too ..
Anyway it was the opportunity to upgrade, 13.1 is EOL already.

**Pull request merged**
