### PR TITLE
added ninja-build and python3-venv as dependencies

### PR DESCRIPTION
**Pull request by cube0x8**
When I start developing in the dev container, I always have to install python3-venv and ninja-build ( `cargo build` fails if they're not installed). So, I added them to the Dockerfile.

### CODE REVIEW

**Comment by tokatoka** [comment]
should we also update rust, clang version too in the Dockerfile?

**Comment by cube0x8** [comment]
yes I guess? I get llvm ver 11 in the container. Not sure about rust... it installs rustc 1.72.0

**Comment by cube0x8** [comment]
Does it make sense to upload llvm to llvm-13? I can do that. Not sure if also rust needs an update tho

**Comment by tokatoka** [comment]
I recommend llvm-15
also we should use nightly. it enables faster feedback evaluation

**Comment by cube0x8** [comment]
Ok for nightly. llvm-15 it's not available on debian bullseye, so i guess we should also update the debian version?

**Pull request merged**
