### PR TITLE
Early return in Generalization Stage if it has metadata already

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

**Comment by addisoncrump** [comment]
Can we not also use `scheduled_count` here?

**Comment by tokatoka** [comment]
I was about to say "Yes, we can"
> The answer is no.

why not?

**Comment by addisoncrump** [comment]
I don't think the change applied is correct. I did a quick test with: 
```rs
                assert_eq!(
                    testcase.has_metadata::<GeneralizedInputMetadata>(),
                    testcase.scheduled_count() > 0
                );
```

This panicked almost immediately.

**Comment by tokatoka** [comment]
> I don't think the change applied is correct. I did a quick test with:

Which fuzzer did you use?
My understanding is when a testcase goes through fuzz_loop(), their scheduled count got incremented.
and everytime this Generalization Stage is executed, the metadata is attached

ah maybe it's unstable, (so no metadata got attached in the end ?)

**Comment by addisoncrump** [comment]
Just `baby_fuzzer_grimoire`.

**Comment by tokatoka** [comment]
actually this is included in #1250 
closing it

**Pull request closed without merging**
