### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by domenukk**

### CODE REVIEW

**Comment by domenukk** [comment]
For future reference: This was done running
`cargo upgrade --workspace --to-lockfile`
of https://github.com/killercup/cargo-edit

**Comment by domenukk** [comment]
We can't update pyo3 due to `grammartec` and capstone due to `frida-gum`

**Comment by tokatoka** [comment]
I opened a pr to frida-rust for bumping capstone version

**Comment by domenukk** [comment]
@andreafioraldi how does a grammartec release work?

**Pull request merged**
