### PR TITLE
Move fuzzers around some more

### PR DESCRIPTION
**Pull request by domenukk**
This renames `others` to `fuzz-anything`, `grammar-aware` to `structure-aware`, and adds a bunch of the baby fuzzers to each of those folders.

@tokatoka @rmalmain what do you think?

### CODE REVIEW

**Comment by tokatoka** [comment]
good to me

**Comment by rmalmain** [comment]
yes looks good to me.
usually we need to update md links after committing to main because some md files contain links to the main branch.
so most of the time we need to do a follow-up PR after breaking these paths

**Comment by domenukk** [comment]
i wonder if the paths should be with `_` instead of `-` to be more consistent with the other folders?

**Comment by domenukk** [comment]
I've moved them to underscore.

**Pull request merged**
