### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by tokatoka**
This was found by https://crates.io/crates/cargo-udeps

### CODE REVIEW

**Comment by tokatoka** [comment]
uh it's used actually.

**Comment by domenukk** [comment]
I think num_cpus may actually no longer be needed, there was a stable rust API for that now IIRC

**Comment by domenukk** [comment]
https://doc.rust-lang.org/stable/std/thread/fn.available_parallelism.html

That's the one

**Comment by domenukk** [comment]
Done in #717

**Pull request closed without merging**
