### PR TITLE
Windows fix

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

**Comment by domenukk** [comment]
```rust
...
clang_rt.asan_static_runtime_thunk-x86_64.lib(asan_malloc_win_thunk.cpp.obj) : error LNK2019: unresolved external symbol __imp___asan_aligned_recalloc referenced in function _aligned_offset_recalloc
libfuzzer_windows_asan.exe : fatal error LNK1120: 12 unresolved externals
clang++: error: linker command failed with exit code 1120 (use -v to see invocation)
```

:/

**Comment by tokatoka** [comment]
can't reproduce that one..

**Comment by tokatoka** [comment]
https://github.com/actions/runner-images/issues/8891

i guess it's not our issue

**Comment by tokatoka** [comment]
doesn't work :<

**Pull request merged**
