### PR TITLE
libafl_qemu: Structured error types for reading/writing registers

### PR DESCRIPTION
**Pull request by langston-barrett**
Makes the errors more programatically inspectable, and instances of `std::error::Error`. Removes the temptation to `impl From<String>` for errors that wrap these. Can be trivially converted to strings, which is demonstrated in this PR. Does introduce new `Copy` bounds, but I think this should be fine?

### CODE REVIEW

**Comment by rmalmain** [comment]
Thanks for the PR, this looks good to me.
There is no problem with the `R` and the `T` bounds being `Copy`.

**Comment by domenukk** [comment]
Clippy is not happy
```rust
error[E0277]: the trait bound `qemu::WriteRegError<i32, u64>: pyo3::IntoPy<pyo3::Py<pyo3::PyAny>>` is not satisfied
    --> libafl_qemu/src/qemu/mod.rs:1210:13
     |
1210 |             self.qemu.write_reg(reg, val).map_err(PyValueError::new_err)
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `pyo3::IntoPy<pyo3::Py<pyo3::PyAny>>` is not implemented for `qemu::WriteRegError<i32, u64>`, which is required by `qemu::WriteRegError<i32, u64>: pyo3::PyErrArguments`
```

**Comment by domenukk** [comment]
CI claims other archs still have some issues, i.e.:
```rust
error[E0308]: mismatched types
  --> libafl_qemu/src/arch/mips.rs:95:9
   |
91 |     fn read_return_address<T>(&self) -> Result<T, String>
   |                                         ----------------- expected `Result<T, std::string::String>` because of return type
...
95 |         self.read_reg(Regs::Ra)
   |         ^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<T, String>`, found `Result<_, ReadRegError<Regs>>`
   |
   = note: expected enum `Result<T, std::string::String>`
              found enum `Result<_, qemu::ReadRegError<arch::mips::Regs>>`
help: use the `?` operator to extract the `Result<_, qemu::ReadRegError<arch::mips::Regs>>` value, propagating a `Result::Err` value to the caller
   |
95 |         self.read_reg(Regs::Ra)?
   |                                +

error[E0277]: the trait bound `T: std::marker::Copy` is not satisfied
   --> libafl_qemu/src/arch/mips.rs:102:34
    |
102 |         self.write_reg(Regs::Ra, val)
    |              ---------           ^^^ the trait `std::marker::Copy` is not implemented for `T`
    |              |
    |              required by a bound introduced by this call
```

**Comment by domenukk** [comment]
Any news?

**Comment by domenukk** [comment]
Still unhappy

**Comment by langston-barrett** [comment]
Will reopen when I have more time to fix it up!

**Comment by domenukk** [comment]
@rmalmain want to finish this?

**Pull request closed without merging**
