### PR TITLE
Clean up samplig_rate, add docs

### PR DESCRIPTION
**Pull request by domenukk**
Follow-up to ##2226, cc @s1341

### CODE REVIEW

**Comment by domenukk** [comment]
Another option could be to do the send backoff time-based

**Comment by tokatoka** [comment]
this thing should be done in event manager

**Comment by tokatoka** [comment]
or do
```
if manager.sample() {
 send_events = true
}
```
it's odd that `Fuzzer` has a member that is about event sendings

**Comment by domenukk** [comment]
Feel free to change it

**Pull request merged**
