### PR TITLE
fix CI and fmt

### PR DESCRIPTION
**Pull request by ToSeven**

### CODE REVIEW

**Comment by tokatoka** [comment]
CI is not triggered.
can you push a dummy commit?

**Comment by tokatoka** [comment]
this is where the error happened
https://github.com/AFLplusplus/LibAFL/actions/runs/6283230258/job/17063481791?pr=1529#step:21:1175
looks like the fuzzer didn't start?

**Comment by ToSeven** [comment]
> this is where the error happened https://github.com/AFLplusplus/LibAFL/actions/runs/6283230258/job/17063481791?pr=1529#step:21:1175 looks like the fuzzer didn't start?

it seems that the binary "fuzzer_libpng" don't exsit? I test it on my pc, all is ok :(
and why donot I trigger the CI?  I shouldn't commit my PR to this branch?

**Comment by tokatoka** [comment]
> and why donot I trigger the CI? I shouldn't commit my PR to this branch?

maybe

**Comment by tokatoka** [comment]
in the end, i guess it didn't work so i just removed that check

**Pull request closed without merging**
