### PR TITLE
Automatically add the comment about executions when a new PR triggers

### PR DESCRIPTION
**Pull request by ToSeven**

### CODE REVIEW

**Comment by domenukk** [comment]
```
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```
Will this go away when it's merged?

**Comment by tokatoka** [comment]
I think we need add tokens(?) for him no?

**Comment by ToSeven** [comment]
Maybe because I don't have any permission.

**Comment by domenukk** [comment]
So I'll try to merge and see what happens.. :D

**Comment by domenukk** [comment]
No success, same error even in main.

**Pull request merged**
