### PR TITLE
sort of fix core affinity on mac arm64

### PR DESCRIPTION
**Pull request by devnexen**
we can t pin to a coreid however we can at least choose the performance cores for our thread.

### CODE REVIEW

**Comment by domenukk** [comment]
If there are 8 cores, 4 perf and 4 non-perf, would we want to use all 8?

**Comment by domenukk** [comment]
Maybe even pinning to the lower 4 cores > perf, pinning to the upper 4 cores > non-perf, or something like that?
Or a differently named function?

**Comment by devnexen** [comment]
> Maybe even pinning to the lower 4 cores > perf, pinning to the upper 4 cores > non-perf, or something like that? Or a differently named function?

non-perf are more fit for background tasks.

**Comment by domenukk** [comment]
Yes I understand, but still, wouldn't 8 fuzzer processes on all 8 cores be faster than 4 on 4 perf cores? (thermal issues ignored)

**Comment by tokatoka** [comment]
it has a clippy error
please fix this
```
error: unused import: `KERN_NOT_SUPPORTED`
   --> libafl/src/bolts/core_affinity.rs:538:60
    |
538 |         thread_policy_flavor_t, thread_policy_t, thread_t, KERN_NOT_SUPPORTED, KERN_SUCCESS,
    |                                                            ^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> libafl/src/lib.rs:65:9
    |
65  |         unused,
    |         ^^^^^^
    = note: `#[deny(unused_imports)]` implied by `#[deny(unused)]`

error: could not compile `libafl` due to previous error
```

thanks

**Pull request merged**
