### PR TITLE
Update libafl_nyx to newest qemu-nyx and nyx-packer

### PR DESCRIPTION
**Pull request by GanbaruTobi**
Fixing some problems with build_nyx_support.sh. 
Providing Makefile for bug in qemu-nyx

!!Did not test on Ubuntu!! Hope somebody will !
Since packer is made for Ubuntu I had to test with modifications which are not part of the commit. But the fuzzers did run.

Still known bug:
The used qemu-nyx cpu is hardcoded in the dependency libnyx. But the cpu should be changed depending on if kvm-nyx is available or not. (But its working anyway)

### CODE REVIEW

**Comment by GanbaruTobi** [comment]
This contains a change of dependency from  https://github.com/syheliel/packer to https://github.com/nyx-fuzz/packer.
I don't know if there was any special feature in syheliel's version, but the nyx-fuzz seems to be more recent and will also be hold in sync with qemu-nyx.

**Comment by syheliel** [comment]
@GanbaruTobi Would you like to fix the format error in https://github.com/AFLplusplus/LibAFL/actions/runs/8729782321/job/23970389808?pr=2070 ?

**Comment by GanbaruTobi** [comment]
I don't understand the errors and I think they are unrelated to my changes? Or maybe point me to what is the format error?

**Comment by syheliel** [comment]
@GanbaruTobi I retriggered CI

**Review by syheliel — COMMENTED** [review]
LGTM

**Comment by domenukk** [comment]
Thanks!

**Pull request merged**
