### PR TITLE
fix(Dockerfile): setup for building libafl_qemu in Docker

### LINKED ISSUE #1895: Can't build libafl_qemu in Dockerfile
Issue confirmed on 8c773a6b850cc1ce20ffca0e0fe34356f30abc76

**Describe the bug**
When trying to build `libafl_qemu` in the docker container, the build errors because it can't find `libafl_qemu/build_linux.rs`.
As I'm trying to use the container as a build environment because my distribution doesn't ship and up-to-date version of LLVM, this is unfortunate.
Should I just modify the Dockerfile for my usecase or is this something I should try and upstream?

**To Reproduce**
1. `docker build -t libafl .`
2. `docker run --name libafl --rm -it libafl`
3. (In the Docker shell) `cargo build -p libafl_qemu`

**Expected behavior**

I would expect the build to complete successfully.

### PR DESCRIPTION
**Pull request by vringar**
Closes #1895

### CODE REVIEW

**Comment by vringar** [comment]
This is currently a draft, as `llvm.sh`  doesn't install llvm-config and also doesn't support installing version 18 on Debian Bookworm which is the current base of the Rust images.

**Comment by tokatoka** [comment]
> llvm.sh doesn't install llvm-config 

for this you can simply apt install llvm-config-18 after running llvm.sh

**Comment by vringar** [comment]
But unfortunately `./llvm.sh 18` fails with the error message:
```
+ apt-get install -y clang-18 lldb-18 lld-18 clangd-18
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package clang-18
E: Unable to locate package lldb-18
E: Unable to locate package lld-18
E: Unable to locate package clangd-18
```

**Comment by vringar** [comment]
Other people have had the same issue and there is a workaround (https://github.com/llvm/llvm-project/issues/62475#issuecomment-1592651066) but I'm unsure if I should implement the workaround or if I should try and land the fix against the [source repo](https://github.com/opencollab/llvm-jenkins.debian.net/tree/master).
Would you be open to accept the workaround?

**Comment by tokatoka** [comment]
you can just include it here if you found the fix

**Comment by vringar** [comment]
Steps to verify this fix works:
```bash
docker build -t libafl . && docker run --name libafl --rm -it libafl
# In the now open shell
cargo build --no-default-features -p libafl_qemu && cargo build --no-default-features -p libafl_qemu --release
```
Also changed the dev container to use the new syntax.

**Comment by tokatoka** [comment]
```
error[E0308]: arguments to this function are incorrect
     --> /home/runner/work/LibAFL/LibAFL/libafl_qemu/src/emu.rs:1533:23
      |
1533  |             let num = libafl_qemu_sys::libafl_add_cmp_hook(gen, exec1, exec2, exec4, exec8, data);
      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
note: expected normal fn, found unsafe fn
     --> /home/runner/work/LibAFL/LibAFL/libafl_qemu/src/emu.rs:1533:60
      |
1533  |             let num = libafl_qemu_sys::libafl_add_cmp_hook(gen, exec1, exec2, exec4, exec8, data);
      |                                                            ^^^
      = note: expected enum `std::option::Option<extern "C" fn(_, _, _) -> _>`
                 found enum `std::option::Option<unsafe extern "C" fn(_, _, _) -> _>`
```
still there's this error (in qemu_fuzzers CI build)

**Comment by tokatoka** [comment]
is this ready?

**Pull request merged**
