### PR TITLE
Recover useful CmpLog updates from #1630

### PR DESCRIPTION
**Pull request by tokatoka**
https://github.com/AFLplusplus/LibAFL/pull/1630 is a failed attempt
as they ctx sensitive cmplog is not doing any better.
this pr recovers some useful stuff from the pr's content.

### CODE REVIEW

**Comment by tokatoka** [comment]
i would run a fuzzbench run before merging this.

**Comment by domenukk** [comment]
Status?

**Comment by tokatoka** [comment]
ready to merge this

**Comment by domenukk** [comment]
Let's goooo

**Pull request merged**
