### PR TITLE
Implement thread-safe AsanGiovese in Rust with snapshots support

### PR DESCRIPTION
**Pull request by andreafioraldi**

### CODE REVIEW

**Comment by domenukk** [comment]
This is cool!

**Comment by domenukk** [comment]
The must_use stuff can be auto fixed with clippy --fix

**Comment by andreafioraldi** [comment]
For a strange reason fuzzbench_qemu is broken

**Comment by andreafioraldi** [comment]
> No lack of coverage, try on your pc it loads 0 initial testcases

cargo clean solved this, weird stuffs

> The must_use stuff can be auto fixed with clippy --fix

No as sometimes we want to not use the bools returned by some methods

**Comment by domenukk** [comment]
I think the link checks for side-effect free functions?

**Comment by andreafioraldi** [comment]
> I think the link checks for side-effect free functions?

I think it ignores unsafe side effects, or more simply it just checks that you are not passing any &mut as argument

**Comment by domenukk** [comment]
> > I think the link checks for side-effect free functions?
> 
> I think it ignores unsafe side effects, or more simply it just checks that you are not passing any &mut as argument

Checked, it looks like it may also ignore non-rust side effects like writes to files, prints, etc.

**Comment by domenukk** [comment]
You could try `--clean-per-run` for `cargo hack`, in case it's not too much disk space we need

**Comment by domenukk** [comment]
And maybe @Mrmaxmeier has a better idea how to safe disk space in CI 😬

**Comment by Mrmaxmeier** [comment]
It might be worth trying to go back to using only the stable toolchain for the feature test job. [Testing nightly features](https://github.com/AFLplusplus/LibAFL/pull/845/commits/8e48261998004999ab5d35a50c03b40ef83184b6) probably produces a second whole bunch of build artifacts.

**Comment by domenukk** [comment]
Random question, does it make sense to share some code between frida asan and this one?

**Comment by andreafioraldi** [comment]
> Random question, does it make sense to share some code between frida asan and this one?

atm no

**Pull request merged**
