### PR TITLE
Added mgr_id to EventManager

### PR DESCRIPTION
**Pull request by domenukk**
This PR should make it easy to identify which client is currently running, and to enable and sdisable features because of it.

### CODE REVIEW

**Comment by domenukk** [comment]
@maxammann @s1341 what do you think of something like this?

**Comment by maxammann** [comment]
Looks good, but it is quite complicated to call:

```rust
            EventManager::<_,_,_,_>::mgr_id(&mgr);
```

complains that:
```
error[E0282]: type annotations needed
   --> src/fuzzer/libafl_setup.rs:109:28
    |
109 |             EventManager::<_,_,_,_>::mgr_id(&mgr);
    |                            ^ cannot infer type

```

`E` is not inferrable. But specificing it manually is very tedious. I actually failed :/

**Comment by domenukk** [comment]
Actually, it should just be `mgr.mgr_id`? Straight forward

**Comment by maxammann** [comment]
@domenukk I just tried again on main and I could not get it working. The reason why I called it in this weird way is to specify a type for the generic `E`. By just calling it on `mgr` Rust is not able to infer `E`:

```
error[E0282]: type annotations needed
   --> src/lib.rs:111:20
    |
111 |     restarting_mgr.mgr_id();
    |                    ^^^^^^ cannot infer type for type parameter `E` declared on the trait `EventManager`
```

The reason for this is that `E` is not part of `LlmpRestartingEventManager`. Therefore we need to specify it manually. Also `mgr_id` does not seem to be implemented for `LlmpRestartingEventManager` but only for `LlmpEventManager` which I do not have access to in the `client_run` function.

**Comment by s1341** [comment]
I like the idea of being able to tell which client we are. We've hacked in support for `asan-cores` and `cmplog-cores` in the frida mode, but it would be better to have a canonical way to do it.

**Pull request merged**
