### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by julihoh**

### CODE REVIEW

**Comment by julihoh** [comment]
Running cargo-outdated
before this pr:
```
Name                          Project  Compat  Latest   Kind    Platform
----                          -------  ------  ------   ----    --------
as-slice->generic-array       0.12.4   0.14.4  Removed  Normal  ---
as-slice->generic-array       0.13.3   0.14.4  Removed  Normal  ---
as-slice->generic-array       0.14.4   ---     Removed  Normal  ---
as-slice->stable_deref_trait  1.2.0    ---     Removed  Normal  ---
bindgen->bitflags             1.2.1    ---     1.3.2    Normal  ---
clap->bitflags                1.2.1    ---     1.3.2    Normal  ---
generic-array->typenum        1.14.0   ---     Removed  Normal  ---
generic-array->version_check  0.9.3    ---     Removed  Build   ---
hashbrown                     0.9.1    ---     0.11.2   Normal  ---
hashbrown->ahash              0.4.7    ---     0.7.5    Normal  ---
heapless->as-slice            0.1.5    ---     Removed  Normal  ---
heapless->generic-array       0.13.3   ---     Removed  Normal  ---
heapless->hash32              0.1.1    ---     0.2.1    Normal  ---
nix                           0.20.2   ---     0.23.0   Normal  ---
nix->bitflags                 1.2.1    ---     1.3.2    Normal  ---
pest->ucd-trie                0.1.3    ---     Removed  Normal  ---
postcard                      0.5.2    ---     0.7.2    Normal  ---
postcard->heapless            0.5.6    ---     0.7.7    Normal  ---
rand_core                     0.5.1    ---     0.6.3    Normal  ---
redox_syscall->bitflags       1.2.1    ---     1.3.2    Normal  ---
rustc_version                 0.3.3    ---     0.4.0    Build   ---
rustc_version->semver         0.11.0   ---     1.0.4    Normal  ---
semver->semver-parser         0.10.2   ---     Removed  Normal  ---
semver-parser->pest           2.1.3    ---     Removed  Normal  ---
windows                       0.18.0   ---     0.21.1   Normal  cfg(windows)
windows->windows_gen          0.18.0   ---     0.21.1   Normal  ---
windows->windows_macros       0.18.0   ---     0.21.1   Normal  ---
windows_macros->windows_gen   0.18.0   ---     0.21.1   Normal  ---
```

after:
```
Name                         Project  Compat  Latest  Kind    Platform
----                         -------  ------  ------  ----    --------
clap->bitflags               1.2.1    ---     1.3.2   Normal  ---
nix                          0.20.2   ---     0.23.0  Normal  ---
nix->bitflags                1.2.1    ---     1.3.2   Normal  ---
redox_syscall->bitflags      1.2.1    ---     1.3.2   Normal  ---
windows                      0.18.0   ---     0.21.1  Normal  cfg(windows)
windows->windows_gen         0.18.0   ---     0.21.1  Normal  ---
windows->windows_macros      0.18.0   ---     0.21.1  Normal  ---
windows_macros->windows_gen  0.18.0   ---     0.21.1  Normal  ---
z3                           0.10.0   ---     0.11.2  Normal  ---
z3->z3-sys                   0.6.3    ---     0.7.1   Normal  ---
```

It completely removes the following crates from the dependency tree:
```
│   │   ├── as-slice v0.1.5
│   │   │   ├── generic-array v0.12.4
│   │   │   │   └── typenum v1.14.0
│   │   │   ├── generic-array v0.13.3
│   │   │   │   └── typenum v1.14.0
│   │   │   ├── generic-array v0.14.4
│   │   │   │   └── typenum v1.14.0
│   │   │   │   [build-dependencies]
│   │   │   │   └── version_check v0.9.3
│   │   │   └── stable_deref_trait v1.2.0
│   │   ├── generic-array v0.13.3 (*)
...
        └── semver-parser v0.10.2
            └── pest v2.1.3
                └── ucd-trie v0.1.3
```
It removes one duplicate `ahash` and one duplicate `rustc_version`.

**Comment by tokatoka** [comment]
I confirmed this does not break windows' api 👍

**Comment by domenukk** [comment]
> should we also try updating `nix`? a quick scan of the changelog didn't reveal anything too major. next to the windows crate, this would be the last outdated crate for the main libafl crate.

let's try

**Comment by domenukk** [comment]
There's this now:
```rust
warning: use of deprecated associated function `nix::errno::<impl nix::errno::Errno>::as_errno`: It's a no-op now; just delete it.
  --> /home/runner/work/LibAFL/LibAFL/libafl/src/bolts/os/pipes.rs:63:62
   |
63 |                 Err(e) => Err(io::Error::from_raw_os_error(e.as_errno().unwrap() as i32)),
   |                                                              ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `nix::errno::<impl nix::errno::Errno>::as_errno`: It's a no-op now; just delete it.
  --> /home/runner/work/LibAFL/LibAFL/libafl/src/bolts/os/pipes.rs:80:62
   |
80 |                 Err(e) => Err(io::Error::from_raw_os_error(e.as_errno().unwrap() as i32)),
   |                                                              
```

**Comment by julihoh** [comment]
Nice 👍

**Pull request merged**
