### PR TITLE
HookId trait and types in libafl_qemu

### PR DESCRIPTION
**Pull request by rbran**
fix: #1795

This created `HookType` and add it to `HookId`, what allows the function `remove_hook` to call the proper `libafl_qemu_sys::libafl_qemu_remove*_hook` function for the received hook.

### CODE REVIEW

**Comment by andreafioraldi** [comment]
Hi, thank you, hookid is WIP, the plan is to have a type for each hook (InstructionHookId, CmpHookId, PreSyscallHookId, etc...) implementing a trait with a removal method, something like `HookId::remove(emu: &Emulator)`.
In this way, hooks id remain just a wrapper around u64 without taking additional space and they are much better for the type system.
If you want to adapt this PR in this way, I'll be happy to merge it.

**Comment by rbran** [comment]
> Hi, thank you, hookid is WIP, the plan is to have a type for each hook (InstructionHookId, CmpHookId, PreSyscallHookId, etc...) implementing a trait with a removal method, something like `HookId::remove(emu: &Emulator)`. In this way, hooks id remain just a wrapper around u64 without taking additional space and they are much better for the type system. If you want to adapt this PR in this way, I'll be happy to merge it.

I adapted the PR, now it uses a trait and specialized structs. NOTE the trait function is `HookId::remove(&self, invalidate_block: bool) -> bool`, the emulator reference is not required.

**Comment by andreafioraldi** [comment]
ty!

**Comment by domenukk** [comment]
This needs a `cargo fmt`.
@andreafioraldi merge?

**Comment by domenukk** [comment]
The QEMU folks are all on holidays or otherwise out of work right now, we'll merge this ASAP :)

**Pull request merged**
