### PR TITLE
Fix staterestore

### LINKED ISSUE #336: Suspicios graph on FuzzBench problably related to the crash restart
https://www.fuzzbench.com/reports/experimental/2021-10-22-libafl/index.html#sqlite3_ossfuzz-summary

### PR DESCRIPTION
**Pull request by tokatoka**
Closes #336

### CODE REVIEW

**Comment by tokatoka** [comment]
Do we want to revert this or find another workaround? @andreafioraldi

**Comment by andreafioraldi** [comment]
Revert is ok

**Comment by tokatoka** [comment]
btw removing #[serde(skip)] at line 51 fixes the error also. which would be better?
https://github.com/serde-rs/serde/issues/2105.

**Comment by andreafioraldi** [comment]
keep serde skip

**Pull request merged**
