### PR TITLE
Add codecov in CI

### PR DESCRIPTION
**Pull request by syheliel**
You can retrieve ${{secrets.CODECOV_TOKEN}} in `https://codecov.io/gh/{USER}/{REPO}`

### CODE REVIEW

**Comment by tokatoka** [comment]
it is not working
https://github.com/AFLplusplus/LibAFL/runs/5819805874

**Comment by syheliel** [comment]
@tokatoka It seems that we have a wrong ${{secrets.CODECOV_TOKEN}}, CODEOV_TOKEN should be the token from a specific repo in `https://codecov.io/gh/{USER}/{REPO}` instead of from the specific user.

**Comment by syheliel** [comment]
@tokatoka Have we set CODECOV_TOKEN in `Settings-Security-Secrets` of Github website? It can only be set by the repo's maintainer

**Comment by tokatoka** [comment]
I don't think I can do that either.
could you take a look at this @domenukk

**Comment by domenukk** [comment]
I tried but I am apparently not admin enough in the aflpp org, no clue who that is @andreafioraldi @vanhauser-thc

**Pull request merged**
