### PR TITLE
Clippy error + warning fixes

### PR DESCRIPTION
**Pull request by addisoncrump**
- Addresses some recent clippy error and warning updates which affected #1503.
- Change clippy to use debug instead of release builds to speed up CI a touch.

### CODE REVIEW

**Comment by addisoncrump** [comment]
Current CI failures are due to a package missing in the python builds. I don't have a way to run the CI locally, can someone else take a look?

**Comment by tokatoka** [comment]
@andreafioraldi 
libafl-qemu-sys doesn't build

**Comment by domenukk** [comment]
@andreafioraldi ping :)

**Comment by domenukk** [comment]
Merging this for now anyway

**Comment by domenukk** [comment]
I'm not sure if building debug will work, we have some linter settings that only warn in debug but fail in release..

**Pull request merged**
