### PR TITLE
Frida Refactor: Separate Frida other helper functions into each Runtime

### PR DESCRIPTION
**Pull request by tokatoka**
This pr separate function hookings in asan runtime to a separate file.
#307

### CODE REVIEW

**Comment by s1341** [comment]
My only comment is that it seems unnecessary to have `asan::asan_*` files. Maybe rename e.g. `asan::asan_errors` to `asan::errors`?

**Comment by tokatoka** [comment]
okay

**Review by s1341 — APPROVED** [review]
Looks great.

**Comment by tokatoka** [comment]
I still have bunch of clippy errors

**Pull request merged**
