### PR TITLE
fix qemu_launcher by moving stop request handling to fuzz_one

### LINKED ISSUE #2373: Error building qemu_launcher
Right now, qemu_launcher doesn't build.
Also, how did this not trigger an CI failure earlier?
```rust
error[E0277]: the trait bound `E: libafl::executors::HasObservers` is not satisfied
   --> src/instance.rs:241:59
    |
241 |             fuzzer.fuzz_loop_for(stages, executor, state, &mut self.mgr, iters)?;
    |                    -------------                          ^^^^^^^^^^^^^ the trait `libafl::executors::HasObservers` is not implemented for `E`, which is required by `libafl::events::MonitorTypedEventManager<libafl::events::LlmpRestartingEventManager<(), libafl::state::StdState<libafl::inputs::BytesInput, libafl::corpus::InMemoryOnDiskCorpus<libafl::inputs::BytesInput>, libafl_bolts::rands::RomuDuoJrRand, libafl::corpus::OnDiskCorpus<libafl::inputs::BytesInput>>, libafl_bolts::shmem::unix_shmem::default::CommonUnixShMemProvider>, M>: libafl::events::EventProcessor<E, Z>`
    |                    |
    |                    required by a bound introduced by this call
    |
    = note: required for `LlmpRestartingEventManager<(), StdState<BytesInput, InMemoryOnDiskCorpus<BytesInput>, ..., ...>, ...>` to implement `libafl::events::EventProcessor<E, Z>`
    = note: 1 redundant requirement hidden
    = note: required for `MonitorTypedEventManager<LlmpRestartingEventManager<(), StdState<BytesInput, ..., ..., ...>, ...>, ...>` to implement `libafl::events::EventProcessor<E, Z>`
note: required by a bound in `libafl::Fuzzer::fuzz_loop_for`
   --> /__w/LibAFL/LibAFL/libafl/src/fuzzer/mod.rs:187:49
    |
187 |     EM: ProgressReporter<State = Self::State> + EventProcessor<E, Self>,
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Fuzzer::fuzz_loop_for`
```

_Originally posted by @domenukk in https://github.com/AFLplusplus/LibAFL/issues/2370#issuecomment-2218046962_

### PR DESCRIPTION
**Pull request by R9295**
@domenukk @tokatoka 

edit:
closes #2373

### CODE REVIEW

**Comment by R9295** [comment]
This is also a hacky fix cause why does Fuzzer with the bound complain but Stdfuzzer doesn't?

**Comment by R9295** [comment]
Yeah hacky was not the right word, strange is more like it:)

**Comment by R9295** [comment]
We should also fix the CI check being skipped in this PR, I'm looking into it

**Comment by rmalmain** [comment]
> We should also fix the CI check being skipped in this PR, I'm looking into it

I'm taking care of it rn, I'll open the pr soon

**Comment by rmalmain** [comment]
originally it was to save resources for the machines running qemu-related fuzzers

**Comment by rmalmain** [comment]
#2395 should avoid this kind of problem in the future.
now QEMU will run more, so it will make CI slower for more PRs as well.

**Pull request merged**
