### PR TITLE
Add HitcountsIterableMapObserver, rename AsMutIter to AsIterMut

### PR DESCRIPTION
**Pull request by domenukk**
This brings back iterators to HitcountsMapObserver.
I would be surprised if it were a lot slower, @tokatoka pleas check :)

### CODE REVIEW

**Comment by tokatoka** [comment]
I am against moving to iterators tbh...
it makes hitcounts slower
I ran forkserver_simple with introspection feature:

Current main build:
```
[PerfMonitor #0] run time: 0h-0m-15s, clients: 1, corpus: 3, objectives: 1, executions: 109072, exec/sec: 7268
Client 000:
  0.0001: Scheduler
  0.0000: Manager
  Stage 0:
    0.0001: GetInputFromCorpus
    0.0059: Mutate
    0.0000: MutatePostExec
    0.7372: TargetExecution
    0.0045: PreExecObservers
    0.0893: PostExecObservers
  Feedbacks:
    0.1598: mapfeedback_metadata_shared_mem
    0.0002: time
    0.0001: CrashFeedback
  0.0027: Not Measured

[PerfMonitor #0] run time: 0h-0m-30s, clients: 1, corpus: 3, objectives: 1, executions: 218192, exec/sec: 7267
Client 000:
  0.0001: Scheduler
  0.0000: Manager
  Stage 0:
    0.0001: GetInputFromCorpus
    0.0059: Mutate
    0.0000: MutatePostExec
    0.7371: TargetExecution
    0.0045: PreExecObservers
    0.0895: PostExecObservers
  Feedbacks:
    0.1597: mapfeedback_metadata_shared_mem
    0.0002: time
    0.0001: CrashFeedback
  0.0027: Not Measured

^C
```

iter branch build:
```
[PerfMonitor #0] run time: 0h-0m-15s, clients: 1, corpus: 3, objectives: 1, executions: 93914, exec/sec: 6255
Client 000:
  0.0003: Scheduler
  0.0000: Manager
  Stage 0:
    0.0002: GetInputFromCorpus
    0.0059: Mutate
    0.0000: MutatePostExec
    0.6957: TargetExecution
    0.0040: PreExecObservers
    0.1477: PostExecObservers
  Feedbacks:
    0.0001: time
    0.0001: CrashFeedback
    0.1437: mapfeedback_metadata_shared_mem
  0.0022: Not Measured

[PerfMonitor #0] run time: 0h-0m-30s, clients: 1, corpus: 3, objectives: 1, executions: 188402, exec/sec: 6273
Client 000:
  0.0003: Scheduler
  0.0000: Manager
  Stage 0:
    0.0002: GetInputFromCorpus
    0.0059: Mutate
    0.0000: MutatePostExec
    0.6954: TargetExecution
    0.0040: PreExecObservers
    0.1479: PostExecObservers
  Feedbacks:
    0.0001: time
    0.0001: CrashFeedback
    0.1438: mapfeedback_metadata_shared_mem
  0.0022: Not Measured
```

it has nearly 1.7x the time spent for the postexec i.e. hitcountsobserver

**Comment by domenukk** [comment]
If the MultiMap has non-16-byte-aligned maps, this will break/be unsafe

**Comment by tokatoka** [comment]
How about making another `MultiMapHitcountsObserver` that can handle multiple maps

**Comment by domenukk** [comment]
Ooh, or we could have one hitcount observer per sub-map

**Pull request merged**
