### PR TITLE
Refactor QEMU snapshot helper and add mmap memory limit

### PR DESCRIPTION
**Pull request by andreafioraldi**

### CODE REVIEW

**Comment by domenukk** [comment]
There are still some "proper" linker errors 
```bash
 = note: mold: error: undefined symbol: libafl_add_edge_hook
          >>> referenced by libafl_qemu.ac06fa3a-cgu.9
          >>>  
```

**Comment by andreafioraldi** [comment]
also the linker stuffs are the same as before

**Comment by andreafioraldi** [comment]
mmmm it is buggy only in the qemu_arm_launcher fuzzer, and makes no sense as I'm building another arm fuzzer and works

**Comment by andreafioraldi** [comment]
qemu is changing too many things...

**Comment by domenukk** [comment]
The CI failure should be fixed in main

**Pull request merged**
