### PR TITLE
Remove `create_serde_registry_for_trait` macro

### LINKED ISSUE #1605: Un-macro SerdeAny
Historically, it was expected that we might allow for multiple registries, but we never used this functionality. We should remove the macro definition `create_serde_registry_for_trait` and unmacro the definition of SerdeAny.

### PR DESCRIPTION
**Pull request by skoriop**
This PR removes the `create_serde_registry_for_trait` macro, extracting the `serdeany_registry` module out of it.

This should close #1605.

### CODE REVIEW

**Comment by domenukk** [comment]
Thanks! Can you run ./scripts/fmt_all.sh please?

**Comment by skoriop** [comment]
Yup, the formatting's fixed now.

**Review by addisoncrump — APPROVED** [review]
This looks correct to me :+1:

**Comment by domenukk** [comment]
Thanks!

**Pull request merged**
