### PR TITLE
Fix fuzzers after HasTestcase (#1123)

### PR DESCRIPTION
**Pull request by domenukk**
cc @matheusbaptistella 

Also: how was this not found in CI? ./fuzzbench simply failed on MacOS.

### CODE REVIEW

**Comment by tokatoka** [comment]
libfuzzer_libpng_cmin & libfuzzer_stb_image_sugar broken.
maybe more

**Comment by matheusbaptistella** [comment]
Hello, I just saw the comment now, what is the problem with the fuzzers?

**Comment by tokatoka** [comment]
don't worry your part is fixed already

**Comment by matheusbaptistella** [comment]
> don't worry your part is fixed already

Oh i didn't mean to do anything wrong, what was the problem with my part?

**Comment by tokatoka** [comment]
we need to implement HasTestcase for corpuses or some fuzzers fail to build

Normally that could be catched in CI, but it turned out the ci was not enabled for a month

**Comment by matheusbaptistella** [comment]
Oh, so my mistake kinda helped realizing CI was disabled hahahaha. I'm still working on `testcase()`, for I believe I'll have to make more changes on it, but if my part is leading to future errors please let me know and so I can correct them!

**Comment by tokatoka** [comment]
let's merge this and fix others later..

**Pull request merged**
