### PR TITLE
libafl-fuzz: fix id collision in Solution corpora

### PR DESCRIPTION
**Pull request by R9295**

### CODE REVIEW

**Comment by domenukk** [comment]
```rust
+ echo No crashes found
```
😬😬😬

**Comment by R9295** [comment]
bruh

**Comment by R9295** [comment]
``ls: cannot access './test/output-cmplog/fuzzer_main/crashes/id:0000*': No such file or directory``

**Comment by tokatoka** [comment]
debugging in #2557

**Pull request closed without merging**
