### PR TITLE
Rename LLMP Timeout message

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

**Comment by tokatoka** [comment]
maybe change the interval too

**Comment by domenukk** [comment]
Ping isn't a good name, just name it "Broker"? And maybe increase the time to 30s or do

**Comment by tokatoka** [comment]
We already stats for every 15 secs
Is sending this message every 30 secs helpful?

**Comment by domenukk** [comment]
It's so we have output when the clients don't send anything for a while (stuck in a loop, etc)

**Comment by domenukk** [comment]
Increase the time to 30 seconds :)

**Pull request merged**
