### PR TITLE
Fixes for frida windows

### PR DESCRIPTION
**Pull request by mineo333**
This PR includes fixes for https://github.com/AFLplusplus/LibAFL/pull/2095 

The main changes include emulating a return to the next instruction for non tail-call hooks as well as removing unix/windows cfg checks for the test fuzzers as they are no longer needed. 

Also properly merged main.

### CODE REVIEW

**Comment by tokatoka** [comment]
can you merge from main?
else it won't trigger ci

**Comment by s1341** [comment]
merging from main doesn't trigger CI... only PR's based on main get CI.

I am reviewing and merging the best bits of this PR manually...

**Comment by tokatoka** [comment]
we can turn it on if you want, shall i?

**Comment by s1341** [comment]
On the one hand, it's not critical for this PR, on the other hand, why not?

**Pull request closed without merging**
