### PR TITLE
Delete introspection feature from libafl_libfuzzer

### PR DESCRIPTION
**Pull request by tokatoka**

### CODE REVIEW

**Comment by tokatoka** [comment]
this one is just not working before
```
toka@DESKTOP-6E54AC0:~/LibAFL/libafl_libfuzzer$ cargo build --features libafl/introspection
error: none of the selected packages contains these features: libafl/introspection
```

**Comment by Mrmaxmeier** [comment]
This (used to) work fine?
```
$ ~/_/L/libafl_libfuzzer ((80311116))> cargo build --features introspection
[...]
```

**Comment by tokatoka** [comment]
https://docs.rs/crate/libafl_libfuzzer/0.13.0/builds/1249871
doc didn't build

**Comment by domenukk** [comment]
would be good to figure out why, right?

**Pull request merged**
