### PR TITLE
Reorder type parameters in the correct order

### PR DESCRIPTION
**Pull request by tokatoka**
this pr sorts the type parameters

I skimmed through every impl and that was a pita 🥙

### CODE REVIEW

**Comment by domenukk** [comment]
I wonder if we could write a custom clippy lint for that :D

**Comment by tokatoka** [comment]
`FeedbackLogic` should comes last, so I reverted that change.

**Comment by domenukk** [comment]
It doesn't have to be last, you just need to change the types here, too:
https://github.com/AFLplusplus/LibAFL/blob/af3d321213973189dfbef864d4035974326d095e/libafl/src/feedbacks/mod.rs#L535

**Comment by tokatoka** [comment]
Personally I feel it is a bit ugly to have `CombinedFeedback<A, B, LogicEagerAnd, I, S>` 😅 
either way is ok

**Comment by domenukk** [comment]
That's the price to pay for alphabetical ordering ;) We have the same situation in other places too:
https://github.com/AFLplusplus/LibAFL/blob/af3d321213973189dfbef864d4035974326d095e/libafl/src/feedbacks/map.rs#L25

**Pull request merged**
