### PR TITLE
Fix libjpeg fuzzer

### PR DESCRIPTION
**Pull request by tokatoka**
reverting #1327 

But I still don't understand why this is bad

### CODE REVIEW

**Comment by tokatoka** [comment]
we can't do this because
```
let observers = executor.observers_mut();
```
observers like cmplog observer doesn't have any edge map for feedback

**Comment by domenukk** [comment]
FYI @s1341

**Comment by addisoncrump** [comment]
I think it's clear that this was not the cause of the bug... instead we should address the specific causes (cmplog needs to check len of compare, `Vec::with_capacity` at every allocation site).

**Comment by tokatoka** [comment]
this is the cause of the 2nd crash. and it's wrong.
this patch means crash in tracing stage = double crash in the fuzzer
removing this will remove double crashes (but doesn't remove false positives)

**Pull request merged**
