### PR TITLE
Rename FavFactor to TestcaseScore; More TestcaseScores

### PR DESCRIPTION
**Pull request by tokatoka**
power schedulers and corpus schedulers use favfactors to compute the parameters now
- PowerMutationalStage is a StdPowerMutationalStage now
- renamed FavFactor to TestcaseScores, and it takes additional `stage` arg

### CODE REVIEW

**Comment by tokatoka** [comment]
depends on #570

**Comment by domenukk** [comment]
Is this PR ready to merge?

**Comment by tokatoka** [comment]
To me, yes.
@andreafioraldi do you agree with this change?

**Comment by andreafioraldi** [comment]
> To me, yes. @andreafioraldi do you agree with this change?

y

**Pull request merged**
