### PR TITLE
Fixing baby_no_std

### PR DESCRIPTION
**Pull request by domenukk**
Seems like the baby_nostd example no longer works.
This moves it to a nightly no_std completely, also on unix.

Windows is likely still broken, though

### CODE REVIEW

**Comment by domenukk** [comment]
CC @Mrmaxmeier

**Comment by domenukk** [comment]
Why would it now be adding `-l c` to the no_std build, while this should clearly only link it for unix:
```rust
fn main() {
    #[cfg(unix)]
    println!("cargo:rustc-link-lib=c")
}
```

**Comment by domenukk** [comment]
Ah lol compile-time of build.rs vs compile-time of the actual target...
Should be fixed

**Comment by Mrmaxmeier** [comment]
FYI: You can enable an "automatically merge this after CI passes" button somewhere in the repo settings `>:)`
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository

**Comment by domenukk** [comment]
Nice stuff!

**Pull request merged**
