### PR TITLE
libafl: `with_capacity` method for `NewHashFeedback`

### PR DESCRIPTION
**Pull request by langston-barrett**
Most of the time, fuzzing campaigns are reasonably long. Accordingly, when using `NewHashFeedback`, you might have good reason to believe that you'll find thousands (or more) different observations with different hashes. When the `HashSet` outgrows its capacity, it can cause reallocation, which is slow. See the following link for more details:

https://doc.rust-lang.org/std/vec/struct.Vec.html#capacity-and-reallocation

### CODE REVIEW

**Comment by domenukk** [comment]
I think it makes sense to always assume a larger large capacity by default

**Comment by langston-barrett** [comment]
> I think it makes sense to always assume a larger large capacity by default

Sure! What do you think would be a good default?

**Comment by domenukk** [comment]
Maybe 4096? 16k?

**Comment by domenukk** [comment]
Feel free to open a separate PR for 4k Initial size

**Comment by langston-barrett** [comment]
@domenukk Thanks! #1049

**Pull request merged**
