### PR TITLE
Basic CmpLog

### PR DESCRIPTION
**Pull request by andreafioraldi**
This PR adds a naive mutator based on the CmpLogMap and refactor a bit the CmpLog stuffs in libafl_targets.

### CODE REVIEW

**Comment by andreafioraldi** [comment]
I hate clippy.

@domenukk `warning: this function has too many lines (126/100)` this has no sense IMO

**Comment by domenukk** [comment]
> I hate clippy.
> 
> @domenukk `warning: this function has too many lines (126/100)` this has no sense IMO

Feel free to add `#[allow(clippy::too_many_lines)]` to the function.
In general shorter fns with descriptive names are more readable, right?

**Comment by andreafioraldi** [comment]
> > I hate clippy.
> > @domenukk `warning: this function has too many lines (126/100)` this has no sense IMO
> 
> Feel free to add `#[allow(clippy::too_many_lines)]` to the function.
> In general shorter fns with descriptive names are more readable, right?

Yes totally, but 126 is not long

**Comment by domenukk** [comment]
That's just the default, I think we can change the threshold somehow (or disable it completely?)

**Pull request merged**
