### PR TITLE
Faster feedback

### PR DESCRIPTION
**Pull request by tokatoka**
Every fuzzers uses *fast* feedback now.

### CODE REVIEW

**Comment by domenukk** [comment]
@bitterbit @andreafioraldi should `fast` be the default here?

**Comment by tokatoka** [comment]
Oh, I only followed #206 
but not the issue #135

**Comment by tokatoka** [comment]
I think objectives should use the fast one. but feedback should stay eager.

**Comment by tokatoka** [comment]
yup I totally missed the problem described in #135 😅 
only some feedbacks can be grouped with `fast`, others should be `eager`
(Like TimeoutFeedback&CrashFeedback that don't change any state)

How about current changes, I try to use the faster one as much as possible

**Comment by bitterbit** [comment]
Last version looks good to me 👍

**Pull request merged**
