### PR TITLE
Restructure the fuzzers folder

### PR DESCRIPTION
**Pull request by rmalmain**
the `fuzzers` subfolder is quite messy nowadays, i think it's time to structure it in some way.
here is a first proposition, i think it can still be greatly improved.

feel free to propose your ideas to make it better

### CODE REVIEW

**Comment by tokatoka** [comment]
fuzzbench should have separate folder, 
others good

**Comment by rmalmain** [comment]
once we consider the structure is good I'll edit the scripts / ci stuff to have things working

**Comment by rmalmain** [comment]
should we move forkserver / qemu fuzzbench in the separate folder as well.
they kind of go into 2 different categories, not sure which one is the best

**Comment by tokatoka** [comment]
i think anything that has fuzzbench in its name should go to fuzzbench folder

**Comment by addisoncrump** [comment]
Seemingly several fuzzers have disappeared... I would expect that the number of deletions be equal to the number of additions here.

**Comment by tokatoka** [comment]
> Seemingly several fuzzers have disappeared... I would expect that the number of deletions be equal to the number of additions here.

Because aflpp_ui is already demonstrated in a more proper example libafl-fuzz
and for accounting, we have the example in another repo.
so we don't really need keep them

**Comment by domenukk** [comment]
The problem with accounting will be that we don't have any CI for it anymore if we remove the fuzzer

**Comment by tokatoka** [comment]
> The problem with accounting will be that we don't have any CI for it anymore if we remove the fuzzer

Ok then maybe it's better not to delete it

**Comment by rmalmain** [comment]
anything else?
if not i'll start editing the ci files

**Comment by rmalmain** [comment]
it's ready to be merged if there is no other comment on the structure.

**Comment by tokatoka** [comment]
yes it's good

**Pull request merged**
