### PR TITLE
Added qemu_cmin

### PR DESCRIPTION
**Pull request by WorksButNotTested**
Corpus minimizer for QEMU mode.

I have used `ForkServerExecutor` to avoid any issues from instability. It would be good to run across multiple cores, but it seems that if I do that, then I end up with duplicates in the corpus directory?

### CODE REVIEW

**Comment by domenukk** [comment]
cmin over multiple cores is not as straight forward I guess? @addisoncrump may have a better idea, but usually you'd distribute the corpus over all cores and cmin each of them, then cmin the whole thing one more time(?)

**Review by domenukk — APPROVED** [review]

**Comment by addisoncrump** [comment]
I mean, as long as the execution time is significantly greater than the map synchronisation time, it should be alright :+1: My concern would be that the libafl components are inherently unsynchronised, but that probably doesn't matter as much for qemu.

**Comment by WorksButNotTested** [comment]
I guess you only have to execute each test case once, so unless you have a very large corpus and very slow target, then maybe it’s not such an issue.

I guess it’s more important for tmin, but that shouldn’t need any synchronisation between cores?

**Comment by domenukk** [comment]
Very large corpora do exist of course, so could be nice to multiprocess at some point in time

**Pull request merged**
