### PR TITLE
Use the new bolts::cli with the frida_libpng sample

### PR DESCRIPTION
**Pull request by s1341**

### CODE REVIEW

**Comment by domenukk** [comment]
Haha yes of course :D
Brain...
Could be nice to move it to a Makefile.toml / cargo-make

**Comment by s1341** [comment]
I think I will get rid of it entirely, and rename the sample to frida_libfuzzer or something like that.

**Comment by domenukk** [comment]
So wrt libpng, I think we should create a Makefile.toml target that can build libpng and use this as testcases in CI
Cc @tokatoka

**Comment by tokatoka** [comment]
yes but then we need to keep harness.ccc

**Comment by tokatoka** [comment]
> and use this as testcases in CI
for linux that is ok.
but for windows I'd prefer a very small c program to test.

**Comment by tokatoka** [comment]
can we merge this?
then I'll make cargo.toml file for this

**Comment by s1341** [comment]
Yes. Let's merge...

**Pull request merged**
