### PR TITLE
Use tcp manager when "tcp_manager" feature is on

### PR DESCRIPTION
**Pull request by s1341**

### CODE REVIEW

**Comment by andreafioraldi** [comment]
I don't get this. LLMP TCP etc can coexist, we don't need a new feature

**Comment by andreafioraldi** [comment]
I think the way to go here to avoid code reuse is a macro that define Launcher with different names (CentralizedLauncher, TCPLauncher etc) changing the trait bound to the different kind of managers

**Comment by s1341** [comment]
Are you sure?

**Comment by domenukk** [comment]
Yes sounds good. We might also have other launchers for other managers in the future

**Comment by domenukk** [comment]
As long as we don't have a better idea, maybe we want to merge this anyway? It's useful to have a tcpmanager enabled launcher sometimes..

**Comment by tokatoka** [comment]
#2302 will supercede tcp manager

**Pull request closed without merging**
