### PR TITLE
Make ByteNegMutator negate, not flip

### PR DESCRIPTION
**Pull request by Scepticz**
Change the ByteNegMutator to negate a byte, not flip it. Flipping a byte is already implemented in ByteFlipMutator.

See issue: https://github.com/AFLplusplus/LibAFL/issues/674

### CODE REVIEW

**Comment by tokatoka** [comment]
thank you!
yes this seems to be a mistake

**Comment by tokatoka** [comment]
could you `cargo fmt` and fix these clippy warnings?
```
error: casting `i16` to `u8` may lose the sign of the value
--> libafl/src/mutators/mutations.rs:274:21
|
274|             *byte = (-(*byte as i16)) as u8;
| ^^^^^^^^^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> libafl/src/lib.rs:17:9
|
17| #![deny(clippy::pedantic)]
| ^^^^^^^^^^^^^^^^
= note: `#[deny(clippy::cast_sign_loss)]` implied by `#[deny(clippy::pedantic)]`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_sign_loss
error: casting `u8` to `i16` may become silently lossy if you later change the type
--> libafl/src/mutators/mutations.rs:274:23
|
274|             *byte = (-(*byte as i16)) as u8;
| ^^^^^^^^^^^^^^help: try: `i16::from(*byte)`
|
= note: `#[deny(clippy::cast_lossless)]` implied by `#[deny(clippy::pedantic)]`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_lossless
warning: `libafl` (lib) generated 5 warnings
error: could not compile `libafl` due to 2 previous errors; 5 warnings emitted
Error: Process completed with exit code [101](https://github.com/AFLplusplus/LibAFL/runs/6917773158?check_suite_focus=true#step:9:102).
```

**Comment by domenukk** [comment]
Isn't the proper fix here to simply add `1` after inverting each bit, assuming normal twos compliment?
Then we don't have to cast etc.

**Comment by syheliel** [comment]
There are still some format problems, can you run ` cargo fmt -- --check` locally and fix the errors?

**Comment by domenukk** [comment]
ping @Scepticz

**Pull request merged**
