### PR TITLE
make dump_registers method public

### PR DESCRIPTION
**Pull request by domenukk**
This allows a user to dump registers at any point in time.

### CODE REVIEW

**Comment by domenukk** [comment]
Actually, maybe I'll let the public methods read the `ucontext_t` internally instead

**Comment by domenukk** [comment]
okay, this is kinda pointless as a method, as the call will tamper with the registers, ucontext should probably be a macro

**Comment by s1341** [comment]
It’s like backtrace. You modify the state by logging the state.

**Comment by domenukk** [comment]
I've set the `ucontext()` fn to always inline, now, that way less should(tm) get clobbered

**Comment by tokatoka** [comment]
there's also a dump register fn in AsanRuntime
https://github.com/AFLplusplus/LibAFL/blob/a80126681e84c5cef9408db1f0eff227e9502153/libafl_frida/src/asan_rt.rs#L2156
I put it for completely debug purpose, and you can delete this

**Comment by s1341** [comment]
Note that the asan reporting code doesn’t use the minibsod. It duplicates the functionality. One reason is because it colorizes register dumps, includes colorized instructions, and includes analysis for related allocations. 

Do we want to try to deduplicate this code?

**Comment by domenukk** [comment]
Maybe we can return the registers as list of tuples (name, value) and then have different prints?

**Comment by domenukk** [comment]
Just read though it, I don't think its worth it deduplicating just the printfs, right?

**Comment by s1341** [comment]
Yeah ok.

**Pull request merged**
