### PR TITLE
Logic stages

### PR DESCRIPTION
**Pull request by tokatoka**
added WhileStage, IfElseStage. then we can make the stages "programmable"

### CODE REVIEW

**Comment by tokatoka** [comment]
you can do skippable with IfElseStage::new(closure, tuple_list!(skippable), tuple_list!()) now.

**Comment by tokatoka** [comment]
ClosureStage is enough to do this

**Comment by tokatoka** [comment]
> ClosureStage is enough to do this

No, I can't immutably borrow `state` in ClosureStage and later call perform().

**Comment by domenukk** [comment]
What's the replacement for skippable stage?

**Comment by tokatoka** [comment]
IfElseStage::new(closure, tuple_list!(skippable), tuple_list!()) is the replacement.

if closure returns true then it's executed, if it returns false, then it's skipped

**Comment by domenukk** [comment]
Seems like a lot more work than before, let's add a wrapper, skipping a stage for a condition is a common use-case

**Comment by tokatoka** [comment]
okay I'll add macro

**Pull request merged**
