### PR TITLE
Frida Refactor: Frida executor

### PR DESCRIPTION
**Pull request by tokatoka**
this pr puts fridaInProceeExecutor into lib
#307

### CODE REVIEW

**Comment by s1341** [comment]
LGTM.

**Comment by tokatoka** [comment]
this could conflict with #368 
so #368 should be first, and I'll fix the conflicts in this one.

**Comment by domenukk** [comment]
Just merged #368

**Comment by tokatoka** [comment]
some clippy checks fails on main branch
I'm waiting for that to get fixed and we can merge this

**Pull request merged**
