### PR TITLE
LibAFL_Libfuzzer: Add clippy warnings

### PR DESCRIPTION
**Pull request by domenukk**
@addisoncrump copy&pasted these from the main lib. It doesn't change much and right now doesn't catch anything, either, but might be nice to have

### CODE REVIEW

**Comment by domenukk** [comment]
I guess we could also make this list a macro

**Comment by domenukk** [comment]
I fear that'll be panful when with the docs build that doesn't have access to all files, tho?

**Comment by addisoncrump** [comment]
We can simply copy it out for the published builds, like we do with renaming of `Cargo.toml`.

**Comment by domenukk** [comment]
Sounds good, but I don't want to do it, let's do a new PR for that :D

**Comment by addisoncrump** [comment]
Lol ok

**Pull request merged**
