### PR TITLE
Use external, custom time function for no_std environments

### PR DESCRIPTION
**Pull request by bitwave**
Added the possibility to create a custom current_millis function for no_std environments (e.g. custom OS, microcontroller, etc.)

### CODE REVIEW

**Comment by bitwave** [comment]
Similar to this code, we can use an external fn:
```rust
    time::Duration::from_millis(1)
```

**Comment by bitwave** [comment]
Can you list me the points where this needs to be implemented?

**Comment by domenukk** [comment]
Likely we need one inside a `#[cfg(test)]` in libafl, plus another one in the `no_std` testcase.
Btw. we could consider a more self-explanotary function name, like `current_millis_no_std` or something? Maybe @andreafioraldi has an opinion here

**Comment by bitwave** [comment]
Additionally we should provide documentation in `docs/` folder how to do this?

**Comment by domenukk** [comment]
A .md file about using libafl in no_std environments would be awesome!

**Pull request merged**
