### PR TITLE
Stop libafl-qemu build early if target_os is not linux.

### PR DESCRIPTION
**Pull request by rmalmain**

### CODE REVIEW

**Comment by domenukk** [comment]
Not sure this is needed, I fixed libafl_qemu for clippy on MacOS (?)

**Comment by rmalmain** [comment]
Does it make sense to check for clippy on macos for libafl_qemu even if doesn't build?

**Comment by domenukk** [comment]
Well it works :D

**Comment by rmalmain** [comment]
Not sure it is easy to develop from Macos without being able to test the fuzzer easily, but I guess it does not cost much.

**Comment by domenukk** [comment]
I don't try to develop Qemu features, but sometimes changes trickle over to other crates...

**Pull request closed without merging**
