### PR TITLE
Add whole-archive feature to libafl_targets

### PR DESCRIPTION
**Pull request by addisoncrump**
This addresses a very annoying issue with libafl_libfuzzer where linkage drops symbols from libafl_targets. It does this by forcing the rustc linkage step to add all object files from libafl_targets, regardless if they are directly referenced or not. Confirmed with GDB, this does cause `__sanitizer_weak_*cmp` to be linked. This should address the issues we see with performance in e.g. PROJ4: https://www.fuzzbench.com/reports/experimental/2023-09-21-libafl/index.html

This is feature-gated as it requires nightly, and the unstable feature cannot be added via rustversion.

### CODE REVIEW

**Comment by addisoncrump** [comment]
Fixes #1540

**Comment by tokatoka** [comment]
@andreafioraldi is this good to you?
I guess we might have a problem like multiple definition

**Comment by addisoncrump** [comment]
Fix is somehow incomplete :ghost: We are still having some weak symbols not being overridden in fuzzbench. Testing locally, it works, but in Fuzzbench, it doesn't!

**Comment by addisoncrump** [comment]
^ This now adds the interceptors as well.

**Comment by domenukk** [comment]
`error: code should be clang-formatted` :P

**Comment by addisoncrump** [comment]
> `error: code should be clang-formatted` :P

Dammit :joy:

**Comment by addisoncrump** [comment]
I've confirmed that this resolves the linkage issues in https://github.com/AFLplusplus/LibAFL/tree/libfuzzer-best

**Comment by domenukk** [comment]
```
  error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/runner/work/LibAFL/LibAFL/libafl_targets/src/lib.rs:2:40
    |
  2 | #![cfg_attr(feature = "whole_archive", feature(packed_bundled_libs))]
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Doesn't seem to work on stable then?

**Comment by addisoncrump** [comment]
Yeah, sadly there's no way to do this with stable.

**Comment by domenukk** [comment]
Merge this then? And mark libfuzzer as nightly?

**Comment by addisoncrump** [comment]
Need to fix CI but I'm not sure what the problem is?

**Comment by tokatoka** [comment]
maybe
```
whole_archive = ["nightly"]
```
to disable it on stable?

**Comment by domenukk** [comment]
So... @andreafioraldi merge or no merge?

**Comment by addisoncrump** [comment]
Rebased.

**Comment by domenukk** [comment]
So ready to merge?

**Comment by addisoncrump** [comment]
We shall see :slightly_smiling_face:

**Comment by domenukk** [comment]
We don't want a dynamic list then?

**Pull request merged**
