### PR TITLE
Use forkserver logic in libafl_cc

### PR DESCRIPTION
**Pull request by tokatoka**
added a method to clang wrapper `forksever()`.
This adds forkserver starter functions to PUT. (also sets shmem up.)

### CODE REVIEW

**Comment by tokatoka** [comment]
:/
maybe this is not good when libafl_cc needs the symbol from libafl_targets
also cargo test doesn't pass this way

**Comment by domenukk** [comment]
The target-specific stuff should definitely be in targets, I think, right?

**Comment by tokatoka** [comment]
yeah that's the way to go; booting forkserver in lib.rs
I thought I could generalize it a bit more and put the shared code into libafl_cc, but that doesn't work 😦

**Comment by tokatoka** [comment]
let me close this for now.
It behaves very strange and I can't figure out what's happening

**Pull request closed without merging**
