### PR TITLE
mopt: seed from state rand instead of current_nanos

### PR DESCRIPTION
**Pull request by Mrmaxmeier**
I ran into a non-determinism issue during debugging caused by this.

### CODE REVIEW

**Comment by domenukk** [comment]
Maybe add a `with_seed` instead? Usually using nanos is fine, right?
In any case you won't have determinism due to differences in timing

**Comment by Mrmaxmeier** [comment]
Yes. Most setup will introduce non-determinism via timing-based decisions. In my case, I've tried avoiding that specifically to reproduce the exact mutations from a previous fuzzing run though.
Is there any benefit to using `current_nanos()`? Querying the state's RNG should be reasonably fast..

**Comment by domenukk** [comment]
Ah didn't see that, in that case it's fine

**Comment by domenukk** [comment]
This will still be an issue when an InProcess mutator respawns, as the mopt state won't be preserved, too.
Not sure why we use a copy of rand instead of the "normal" one cc @tokatoka

**Comment by tokatoka** [comment]
thank you!

>  a copy of rand instead of the "normal" one 

what do you mean by "copy of rand"?

**Comment by domenukk** [comment]
You create your own rand here, isntead of using that from State, right?

**Pull request merged**
