### PR TITLE
Update cmplog-routines-pass.cc

### PR DESCRIPTION
**Pull request by tokatoka**
update from latest afl++

### CODE REVIEW

**Comment by domenukk** [comment]
@vanhauser-thc should we try to merge the passes at some point, maybe in a sub repo?

**Comment by tokatoka** [comment]
oh wait. i've not tested at all.

**Comment by tokatoka** [comment]
> should we try to merge the passes at some point, maybe in a sub repo?

I'm working on the other two cmplog passes now.
instruction hook and switches hook

**Comment by vanhauser-thc** [comment]
> @vanhauser-thc should we try to merge the passes at some point, maybe in a sub repo?

would make things easier I guess :)

**Comment by tokatoka** [comment]
yes this is a good idea because i also want to keep some passes synced with AFL++

**Pull request merged**
